loaded_h_0(function(_){var window=this;
_.t("sb_wiz");

_.v();
_.t("aa");

_.v();
_.t("abd");
var qQD=function(a){typeof a==="string"&&(a=_.am(a));if(a)return _.Im(a,"display")!=="none"&&_.Im(a,"visibility")!=="hidden"&&a.offsetHeight>0},rQD=function(a){let b="",c=21;for(let d=0;d<a.length;d++)d%4!=3&&(b+=String.fromCharCode(a[d]^c),c++);return b},sQD=function(a){let b=0;for(const c in a)if(a[c].e)if(a[c].b)b++;else return!1;return b>0},xQD=function(a={}){const b={};b[tQD]={e:!!a[tQD],b:!qQD(uQD)};b[vQD]={e:!!a[vQD],b:!qQD(wQD)};return b},yQD=function(a){const b=[];for(const c in a)a[c].e&&
b.push(`${c}:`+(a[c].b?"1":"0"));return b.join(",")},AQD=function(a,b){a=String(a);b&&(a+=`,${b}`);google.log(zQD,a)},BQD=function(a,b,c=2){if(c<1)AQD(7,b);else{var d=new Image;d.onerror=()=>{BQD(a,b,c-1)};d.src=a}};var uQD=rQD([97,119,115,111,107]),wQD=rQD([97,119,115,111,107,123]),CQD=rQD([118,115,121,107,108,124,104,119,68,127,114,105,114]),zQD=rQD([101,126,118,102,118,125,118,109,126]),DQD=rQD([116,116,115,108]),tQD=rQD([113,115,99,107]),vQD=rQD([113,115,117,107]),EQD=rQD([58,127,122,103,121,126,127,98,104,51,109,124,118,123,15,76,81,90,13,95,67,76,64,118]);_.fh("abd",{init:function(a={}){if(a[DQD]&&qQD(CQD)){a=xQD(a);var b=yQD(a);sQD(a)?AQD(1,"0,"+b):AQD(0,b);(0,_.sf)(()=>{BQD(EQD,"aa")})}}});
_.v();
var yNd,xNd,vNd,HNd,GNd,ANd,zNd,wNd;yNd=function(a){return vNd(a).then(b=>wNd?xNd(a,b):b.response)};xNd=async function(a,b){const c=b.EGe;let d=2;c==="s"?d=0:c==="a"&&(d=1);return _.oXb(b.response,d,a,e=>Promise.resolve(vNd(e).then(f=>f.response)),b.eventId)};
vNd=function({method:a,url:b,mRc:c,Fj:d,lG:e,headers:f}){const g=_.rf(),h=zNd?zNd():new _.qr;h.listen("complete",l=>{l=l.target;var n=!1;l.getResponseHeader("X-Sorry-Redirect")&&(n=!0);if(l.isSuccess()){_.Go(d,"st");const r=l.AA();d.By("bs",r.length);r||g.reject(new _.nQb("Async response error",e,{s:l.getStatus(),r,isr:n,rurl:ANd(l)}));var q;(n=l.getResponseHeader("x-google-gfe-backend-request-info"))&&(n=/eid=([^,]+)/.exec(n))&&(q=n[1]);g.resolve({response:r,EGe:l.getResponseHeader("x-sg-cs")||"u",
eventId:q})}else _.Go(d,"ft"),d.log(),(q=l.getStatus())?(q={s:q,isr:n,rurl:ANd(l)},l.vda===7&&(q.ab=1),g.reject(new _.nQb("Async request error",e,q))):g.reject(new _.nQb("Async network error",e))});const k=g.promise.vB(l=>{if(l instanceof _.af)h.abort();else throw l;});_.Go(d,"fr");h.setWithCredentials(_.SQb);f=f?Object.fromEntries(f):void 0;h.send(b,a,c,f);return k};_.BNd=function(a){return!a||a instanceof Map?new Map(a||[]):new Map(Object.entries(a))};
_.PE=function(a,b,c,d,e,f,g={},h,k="insert",l=!1,n=!1){const q=_.CNd(a);q.start();b=_.BNd(b);g=_.BNd(g);return _.DNd(a,b,g,q,"",e,c,h,d,f,k,l,n)};_.DNd=function(a,b,c,d,e,f,g,h,k,l,n,q=!1,r=!1){b.set("_fmt",q?"json":"jspb");f!=null&&c.set("q",f);c=_.bRb(a,b,c,"GET",e,g,h,k,l,n);e="";g?e=g:h&&(e=h);return _.ENd({method:"GET",url:c,Fj:d,lG:a,headers:_.ZQb(),Fq:b},r,e)};
_.ENd=function(a,b=!1,c=""){let d;const e=(d=a.Fq)==null?void 0:d.get("_fmt");if(e!=="json"&&e!=="jspb")throw Error("hk");a.Fj||(a.Fj=_.CNd(a.lG));return yNd(a).then(f=>{if(b){let h;(h=a.Fj)==null||h.log()}f.startsWith(")]}'\n")&&(f=f.substr(5));let g;try{g=JSON.parse(f)}catch(h){return _.rh(h)}return _.Yf(g)&&(g=_.yka(g),f=g.__err__,f!==void 0)?_.rh(f):e!=="jspb"||g instanceof Array?_.lg(g):_.rh()}).catch(f=>f instanceof _.nQb&&FNd?GNd(f,b,a,c):_.rh(f))};
HNd=function(a,b){const c=b.urlParams?new Map(b.urlParams):new Map;try{const d=new _.Dn(b.url);_.Jn(d,"google_abuse",a);c.set("google_abuse",a);b.url=d.toString();b.urlParams=c}catch(d){}return b};GNd=function(a,b,c,d){if(_.IQb(a))return a=_.JQb(a),c=HNd(a,c),_.ENd(c,b,d);const e=_.KQb(a);if(e){_.MQb(e,d);if(!_.FQb)return _.bg((0,_.OQb)(e).then(f=>{_.NQb(e,d);c=HNd(f,c);return _.ENd(c,b,d)}),_.HQb);if(_.PQb)return _.FQb.promise.then(()=>_.ENd(c,b,d))}return _.rh(a)};
_.CNd=function(a){const b=new _.Ho("async");b.Hc("astyp",a);return b};ANd=function(a){try{return a.Oo?a.Oo.responseURL:""}catch(b){return""}};zNd=null;wNd=_.bYb;var FNd=_.aYb;
_.t("async");


_.v();
var UJd,VJd,WJd,aKd,YJd,ZJd,$Jd;UJd=function(){const a=new _.xf;a.callback(null);return a};WJd=[];_.XJd=function(a){if(!a.length)return UJd();const b=WJd.length;_.Ea(WJd,a);if(b)return VJd;a=WJd;const c=function(){var d=a.shift();d=_.KE(d);a.length&&_.wf(d,c,c);return d};return VJd=c()};
_.KE=function(a,b){const c=b||{};b=c.document||document;const d=_.jc(a).toString(),e=(new _.iIa(b)).createElement("SCRIPT");var f={nCd:e,pba:void 0};const g=new _.xf(YJd,f);let h=null;const k=c.timeout!=null?c.timeout:5E3;k>0&&(h=window.setTimeout(function(){ZJd(e,!0);g.oa(new $Jd(1,"Timeout reached for loading script "+d))},k),f.pba=h);e.onload=e.onreadystatechange=function(){e.readyState&&e.readyState!="loaded"&&e.readyState!="complete"||(ZJd(e,c.V9c||!1,h),g.callback(null))};e.onerror=function(){ZJd(e,
!0,h);g.oa(new $Jd(0,"Error while loading script "+d))};f=c.attributes||{};_.Mc(f,{type:"text/javascript",charset:"UTF-8"});_.hm(e,f);_.Wc(e,a);aKd(b).appendChild(e);return g};aKd=function(a){const b=_.cm("HEAD",a);return b&&b.length!==0?b[0]:a.documentElement};YJd=function(){if(this&&this.nCd){const a=this.nCd;a&&a.tagName=="SCRIPT"&&ZJd(a,!0,this.pba)}};
ZJd=function(a,b,c){c!=null&&_.ca.clearTimeout(c);a.onload=()=>{};a.onerror=()=>{};a.onreadystatechange=()=>{};b&&window.setTimeout(function(){_.wm(a)},0)};$Jd=function(a,b){let c="Jsloader error (code #"+a+")";b&&(c+=": "+b);_.ba.call(this,c);this.code=a};_.vi($Jd,_.ba);
_.t("bgd");
var SQD=function(a){var b=new LQD(a);a?_.z(b,1)?_.z(b,2)?(a=_.z(b,1),b=_.z(b,2),MQD=!0,NQD=a,OQD=b,PQD&&QQD()):RQD(14):RQD(13):RQD(12)},TQD=function(){RQD(11)},QQD=function(){UQD?window.document.readyState===VQD?WQD():XQD?_.jn(window,"load",WQD):_.jn(window.document,YQD,WQD):ZQD?(0,_.Vn)(WQD,ZQD):WQD()},WQD=function(){_.wf(_.KE(_.Bua(NQD),{V9c:!0}),$QD,aRD)},aRD=function(){RQD(3)},cRD=function(a){try{a.invoke(bRD)}catch(b){RQD(8)}},hRD=function(){let a=null;try{a=new window.botguard.bg(OQD)}catch(b){RQD(6);
return}a.invoke?dRD&&(eRD&&_.we(window,"click",_.ti(fRD,a),!0),gRD&&_.we(window,"unload",()=>cRD(a)),eRD||gRD||cRD(a)):RQD(7)},fRD=function(a,b){if(b=_.Cm(b.target,"A")){var c=!1;if(b.hasAttribute("data-al"))c=!0;else{let d=b;for(;d;){if(d.id==="tads"||d.id==="tadsb"){c=!0;break}d=_.sg(d)}}c&&(iRD(b,"href",a)||iRD(b,"data-rw",a))}},iRD=function(a,b,c){var d=a.getAttribute(b);if(!d||!d.includes("aclk?"))return!1;c=c.invoke();c=typeof c!=="string"||c.length>(jRD?1500:500)?void 0:c;if(!c)return!0;d=
_.pc(d+`&bg=${c}`);a.setAttribute(b,_.lc(d));return!0},$QD=function(){kRD&&(window.botguard?window.botguard.bg?lRD?(0,_.Vn)(hRD,lRD):hRD():RQD(5):RQD(4))},bRD=function(a){mRD&&(a?a.length>1875?RQD(10):RQD(a):RQD(9))},RQD=function(a){google.log("srpbgd",String(a))},LQD=class extends _.m{constructor(a){super(a)}};var MQD=!1,OQD="",NQD="",PQD=!1,ZQD=0,UQD=!1,kRD=!1,lRD=0,dRD=!1,gRD=!1,eRD=!1,mRD=!1,XQD=!1,VQD="complete",YQD="load",jRD=!1;
_.fh("bgd",{init:function(a){if(!MQD)if(a)if("et"in a&&(lRD=a.et),"ed"in a&&(ZQD=a.ed),a.ea&&(UQD=!0),a.ei&&(dRD=!0),a.lr&&(jRD=!0),a.eu&&(gRD=!0),a.ac&&(eRD=!0),a.ep&&(mRD=!0),a.er&&(kRD=!0),a.el&&(PQD=!0),a.as)_.PE("bgasy",{}).then(SQD,TQD);else if(a.i)if(a.p){a.wl&&(XQD=!0);a.li&&(VQD="interactive",YQD="DOMContentLoaded");var b=String(a.i);a=String(a.p);MQD=!0;NQD=b;OQD=a;PQD&&QQD()}else RQD(2);else RQD(1);else RQD(0)}});
_.v();
_.TZC=function(){const a=_.Ed().host.match("google(?:\\.[a-z]{2,3}){1,2}$");return a?a[0]:null};
_.t("foot");
_.fh("foot",{init:function(a){if(a.dv!==void 0&&a.dv!=="")try{_.of.set("DV",a.dv,{xaa:600})}catch(b){_.$e(b,{Gf:{src:"foot"}})}if(a.dvct!==void 0&&a.dvct!=="")try{_.of.set("CONSISTENCY",a.dvct,{xaa:600,domain:_.TZC()})}catch(b){_.$e(b,{Gf:{src:"foot"}})}}});
_.v();
var sch,vch,rch,tch,pch;sch=function(){_.mn(pch);(0,_.qch)("kne","enabled");pch=_.we(rch,"keydown",a=>{a.keyCode!==13&&a.keyCode!==32||(0,_.qch)("kne","selected")})};vch=function(){_.mn(tch);tch=_.jn(rch,"mousedown",()=>{_.uch()},{capture:!0})};_.ych=function(){_.mn(tch);tch=_.we(rch,"keydown",a=>{_.wch.indexOf(a.keyCode)!==-1&&_.xch()})};_.uch=function(){_.Yl.remove(rch,_.zch);_.Ach&&_.mn(pch);_.ych()};_.xch=function(){_.Yl.add(rch,_.zch);_.Ach&&sch();vch()};
_.Bch=function(){return _.Yl.contains(rch,_.zch)};_.Ach=!1;_.wch=[9];rch=document.documentElement;
_.t("kyn");
var $RE=function(a){_.zch="zAoYTe";_.qch=a;_.ych()};_.fh("kyn",{init:function(){$RE((a,b)=>{const c=_.Ng();c.Hc(a,b);c.log()})}});
_.v();
var T9c,V9c,X9c;T9c=function(a){var b;(b=!a.parentElement)||(a.ownerDocument&&a.ownerDocument.defaultView?(b=a.ownerDocument.defaultView.getComputedStyle(a))&&b.visibility==="hidden"?b=!1:(b=a.getBoundingClientRect(),b=b.width>0&&b.height>0):b=!0);return b?a:T9c(a.parentElement)};V9c=function(a){if(a){var b=new U9c;for(const f of Object.keys(a)){var c=document.getElementById(f)||document.documentElement.querySelector(`img[data-iid="${f}"]`);if(c){var d=b,e=a[f];d.oa.oa(c,e)||d.Aa.oa(c,e)}}}};
_.W9c=function(){V9c(google.ldi);V9c(google.pim);google.lfj?google.sx(null,()=>{V9c(google.ldilf)}):google.dclc(()=>{V9c(google.ldilf)})};X9c=class{constructor(a){this.rootMargin=a;this.jj=null}uMa(){if(this.jj)return!0;try{return this.jj=new IntersectionObserver((a,b)=>{a=a.filter(c=>c.isIntersecting);for(const c of a)a=c.target,this.Ca(a),b.unobserve(a)},{rootMargin:this.rootMargin,threshold:[0]}),!0}catch(a){return!1}}};var Y9c=class extends X9c{constructor(){super("0px");this.Aa=new Map;this.Ba=new Map}oa(a,b){if(a.hasAttribute("data-atf"))return!1;if(this.uMa()){this.Ba.set(a,b);b=T9c(a);if(b===a){var c;a:{for(c=a;c;c=c.parentElement)if(c.tagName==="G-SCROLLING-CAROUSEL"||c.classList.contains("XNfAUb"))break a;c=null}c&&(b=c)}(c=this.Aa.get(b))?c.push(a):this.Aa.set(b,[a]);this.jj.observe(b);return!0}return!1}Ca(a){if(a=this.Aa.get(a))for(const b of a)a=this.Ba.get(b),_.DRb(b,a)}};var Z9c=class extends X9c{constructor(){super("400px");this.Aa=new Map}oa(a,b){(google.c.timl||Number(a.getAttribute("data-atf"))&1?0:this.uMa())?(this.Aa.set(a,b),this.jj.observe(a)):_.DRb(a,b);return!0}Ca(a){const b=this.Aa.get(a);_.DRb(a,b)}};var U9c=class{constructor(){this.oa=new Y9c;this.Aa=new Z9c}};
_.t("lli");
_.W9c();
_.v();
_.Biv=!!(_.qi[26]&16);_.Civ=!!(_.qi[26]&32);_.Div=!!(_.qi[26]&64);_.Eiv=!!(_.qi[26]&256);
var X9o,Y9o,Z9o,$9o,a$o,b$o,c$o,d$o,f$o,h$o,i$o,g$o,k$o,l$o,n$o,o$o,q$o;_.W9o=function(){return V9o=V9o||new _.ue};X9o=function(a){_.cn.call(this,"serverreachability",a)};Y9o=function(a){const b=_.W9o();b.dispatchEvent(new X9o(b,a))};Z9o=function(a,b){_.cn.call(this,"statevent",a);this.stat=b};$9o=function(a){const b=_.W9o();b.dispatchEvent(new Z9o(b,a))};a$o=function(a,b,c,d){_.cn.call(this,"timingevent",a);this.size=b;this.rtt=c;this.RXa=d};
b$o=function(a,b,c){const d=_.W9o();d.dispatchEvent(new a$o(d,a,b,c))};c$o=function(a,b){if(typeof a!=="function")throw Error("jt");return _.ca.setTimeout(function(){a()},b)};d$o=function(){this.Vm=null;this.oa=!0};
f$o=function(a,b,c,d){this.Ca=a;this.Aa=b;this.Da=c;this.Nb=d||1;this.Yo=new _.me(this);this.pba=45E3;this.Za=null;this.Ka=!1;this.Ea=this.Ha=this.Pa=this.zE=this.Va=this.Sb=this.Ta=null;this.Ua=[];this.oa=null;this.Na=0;this.hga=this.Ma=null;this.Lb=-1;this.kb=!1;this.Cb=0;this.Bb=null;this.Vb=this.ob=this.Rb=this.Gb=!1;this.Ba=new e$o};
h$o=function(a,b){const c=new d$o;c.debug("TestLoadImage: loading "+a);if(_.ca.Image){const d=new Image;d.onload=_.ti(g$o,c,"TestLoadImage: loaded",!0,b,d);d.onerror=_.ti(g$o,c,"TestLoadImage: error",!1,b,d);d.onabort=_.ti(g$o,c,"TestLoadImage: abort",!1,b,d);d.ontimeout=_.ti(g$o,c,"TestLoadImage: timeout",!1,b,d);_.ca.setTimeout(function(){if(d.ontimeout)d.ontimeout()},1E4);d.src=a}else b(!1)};
i$o=function(a,b){const c=new d$o,d=new AbortController,e=setTimeout(()=>{d.abort();g$o(c,"TestPingServer: timeout",!1,b)},1E4);fetch(a,{signal:d.signal}).then(f=>{clearTimeout(e);f.ok?g$o(c,"TestPingServer: ok",!0,b):g$o(c,"TestPingServer: server error",!1,b)}).catch(()=>{clearTimeout(e);g$o(c,"TestPingServer: error",!1,b)})};g$o=function(a,b,c,d,e){try{a.debug(b),e&&(e.onload=null,e.onerror=null,e.onabort=null,e.ontimeout=null),d(c)}catch(f){}};k$o=function(){this.oa=new j$o};
l$o=function(a,b,c){return c&&c.Nme?c.Nme[a]||b:b};
n$o=function(a){this.Ef=0;this.Ba=[];this.oa=new d$o;this.ld=this.Id=this.ob=this.wc=this.Aa=this.Kd=this.Va=this.kb=this.Ha=this.qc=this.Ka=null;this.Di=this.xc=0;this.Lf=l$o("failFast",!1,a);this.Za=this.Na=this.Ma=this.Ea=this.Da=null;this.Bc=!0;this.Rb=this.ze=this.Bb=-1;this.Mc=this.Pa=this.Ua=0;this.tF=l$o("baseRetryDelayMs",5E3,a);this.Mha=l$o("retryDelaySeedMs",1E4,a);this.Mf=l$o("forwardChannelMaxRetries",2,a);this.Od=l$o("forwardChannelRequestTimeoutMs",2E4,a);this.L0b=a&&a.vFb||void 0;
this.Kg=a&&a.dUf||void 0;this.Sf=a&&a.fRe||!1;this.Lb=void 0;this.Cb=a&&a.fYc||!1;this.Gb="";this.Ca=new m$o(a&&a.bNf);this.fw=Math.min(a&&a.ETf||1E3,1E3);this.vD=new k$o;this.Vb=a&&a.YKb||!1;this.Sb=a&&a.jPf||!1;this.Vb&&this.Sb&&(this.Sb=!1);this.Hg=a&&a.LLf||!1;a&&a.Mbd&&this.oa.Mbd();a&&a.YPf&&(this.Bc=!1);this.Nc=!this.Vb&&this.Bc&&a&&a.h7d||!1;this.Cd=void 0;a&&a.btd&&a.btd>0&&(this.Cd=a.btd);this.Fp=void 0;this.Xb=0;this.Nb=!1;this.vd=this.Ta=null};o$o=function(){};_.p$o=function(){return new o$o};
q$o=function(){_.cn.call(this,"x")};_.vi(q$o,_.cn);var r$o=function(){_.cn.call(this,"w")};_.vi(r$o,_.cn);var V9o=null;_.vi(X9o,_.cn);_.vi(Z9o,_.cn);_.vi(a$o,_.cn);d$o.prototype.Mbd=function(){this.oa=!1};
var s$o=function(a,b,c,d,e,f){a.info(function(){if(a.oa)if(f){var g="";var h=f.split("&");for(let l=0;l<h.length;l++){var k=h[l].split("=");if(k.length>1){const n=k[0];k=k[1];const q=n.split("_");g=q.length>=2&&q[1]=="type"?g+(n+"="+k+"&"):g+(n+"=redacted&")}}}else g=null;else g=f;return"XMLHTTP REQ ("+d+") [attempt "+e+"]: "+b+"\n"+c+"\n"+g})},t$o=function(a,b,c,d,e,f,g){a.info(function(){return"XMLHTTP RESP ("+d+") [ attempt "+e+"]: "+b+"\n"+c+"\n"+f+" "+g})},v$o=function(a,b,c,d){a.info(function(){return"XMLHTTP TEXT ("+
b+"): "+u$o(a,c)+(d?" "+d:"")})},w$o=function(a,b){a.info(function(){return"TIMEOUT: "+b})};d$o.prototype.debug=function(){};d$o.prototype.info=function(){};
var u$o=function(a,b){if(!a.oa)return b;if(!b)return null;try{const f=JSON.parse(b);if(f)for(let g=0;g<f.length;g++)if(Array.isArray(f[g])){var c=f[g];if(!(c.length<2)){var d=c[1];if(Array.isArray(d)&&!(d.length<1)){var e=d[0];if(e!="noop"&&e!="stop"&&e!="close")for(let h=1;h<d.length;h++)d[h]=""}}}return _.rNa(f)}catch(f){return a.debug("Exception parsing expected JS array - probably was not JS"),b}};var e$o=function(){this.Ba=null;this.oa="";this.Aa=!1},x$o=function(a,b){switch(a){case 0:return"Non-200 return code ("+b+")";case 1:return"XMLHTTP failure (no data)";case 2:return"HttpConnection timeout";default:return"Unknown error"}},y$o={},z$o={};f$o.prototype.setTimeout=function(a){this.pba=a};
var B$o=function(a,b,c){a.zE=1;a.Pa=_.PLa(b.clone());a.Ea=c;a.Gb=!0;A$o(a,null)},A$o=function(a,b){a.Va=Date.now();C$o(a);a.Ha=a.Pa.clone();_.OLa(a.Ha,"t",a.Nb);a.Na=0;const c=a.Ca.Cb;a.Ba=new e$o;a.oa=D$o(a.Ca,c?b:null,!a.Ea);a.Cb>0&&(a.Bb=new _.ZFb((0,_.xe)(a.Xb,a,a.oa),a.Cb));a.Yo.listen(a.oa,"readystatechange",a.qc);b=a.Za?_.Kc(a.Za):{};a.Ea?(a.Ma||(a.Ma="POST"),b["Content-Type"]="application/x-www-form-urlencoded",a.oa.send(a.Ha,a.Ma,a.Ea,b)):(a.Ma="GET",a.oa.send(a.Ha,a.Ma,null,b));Y9o(1);s$o(a.Aa,
a.Ma,a.Ha,a.Da,a.Nb,a.Ea)};f$o.prototype.qc=function(a){a=a.target;const b=this.Bb;b&&a.Qca()==3?(this.Aa.debug("Throttling readystatechange."),b.fire()):this.Xb(a)};f$o.prototype.Xb=function(a){try{a==this.oa&&E$o(this)}catch(b){this.Aa.debug("Failed call to OnXmlHttpReadyStateChanged_"),F$o(this)}finally{}};
var E$o=function(a){const b=a.oa.Qca();var c=a.oa.vda,d=a.oa.getStatus();if(!(b<3||b==3&&!F$o(a))){a.kb||b!=4||c==7||(c==8||d<=0?Y9o(3):Y9o(2));G$o(a);var e=a.oa.getStatus();a.Lb=e;c=H$o(a);F$o(a)||a.Aa.debug(function(){return"No response text for uri "+a.Ha+" status "+e});a.Ka=e==200;t$o(a.Aa,a.Ma,a.Ha,a.Da,a.Nb,b,e);if(a.Ka){if(a.Rb&&!a.ob)if(d=I$o(a))v$o(a.Aa,a.Da,d,"Initial handshake response via X-HTTP-Initial-Response"),a.ob=!0,J$o(a,d);else{a.Ka=!1;a.hga=3;$9o(12);K$o(a);L$o(a);return}a.Gb?
M$o(a,b,c):(v$o(a.Aa,a.Da,c,null),J$o(a,c));b==4&&K$o(a);a.Ka&&!a.kb&&(b==4?N$o(a.Ca,a):(a.Ka=!1,C$o(a)))}else a.oa.ifb(),e==400&&c.indexOf("Unknown SID")>0?(a.hga=3,$9o(12)):(a.hga=0,$9o(13)),K$o(a),L$o(a)}},I$o=function(a){return a.oa&&(a=_.bWb(a.oa,"X-HTTP-Initial-Response"))&&!_.ha(a)?a:null},H$o=function(a){if(!O$o(a))return a.oa.AA();const b=a.oa.getResponse();if(b==="")return"";let c="";const d=b.length,e=a.oa.Qca()==4;if(!a.Ba.Ba){if(typeof TextDecoder==="undefined")return K$o(a),L$o(a),"";
a.Ba.Ba=new _.ca.TextDecoder}for(let f=0;f<d;f++)a.Ba.Aa=!0,c+=a.Ba.Ba.decode(b[f],{stream:!(e&&f==d-1)});b.length=0;a.Ba.oa+=c;a.Na=0;return a.Ba.oa},F$o=function(a){return a.oa?a.Ba.Aa?!0:!(!a.oa.AA()&&!a.oa.getResponse()):!1},O$o=function(a){return a.oa?a.Ma=="GET"&&a.zE!=2&&a.Ca.Sf:!1},M$o=function(a,b,c){let d=!0,e;for(;!a.kb&&a.Na<c.length;)if(e=P$o(a,c),e==z$o){b==4&&(a.hga=4,$9o(14),d=!1);v$o(a.Aa,a.Da,null,"[Incomplete Response]");break}else if(e==y$o){a.hga=4;$9o(15);v$o(a.Aa,a.Da,c,"[Invalid Chunk]");
d=!1;break}else v$o(a.Aa,a.Da,e,null),J$o(a,e);O$o(a)&&a.Na!=0&&(a.Ba.oa=a.Ba.oa.slice(a.Na),a.Na=0);b!=4||c.length!=0||a.Ba.Aa||(a.hga=1,$9o(16),d=!1);a.Ka=a.Ka&&d;d?c.length>0&&!a.Vb&&(a.Vb=!0,b=a.Ca,b.Aa==a&&b.Nc&&!b.Nb&&(b.oa.info("Great, no buffering proxy detected. Bytes received: "+c.length),Q$o(b),b.Nb=!0,$9o(11))):(v$o(a.Aa,a.Da,c,"[Invalid Chunked Response]"),K$o(a),L$o(a))},P$o=function(a,b){var c=a.Na,d=b.indexOf("\n",c);if(d==-1)return z$o;c=Number(b.substring(c,d));if(isNaN(c))return y$o;
d+=1;if(d+c>b.length)return z$o;b=b.slice(d,d+c);a.Na=d+c;return b};f$o.prototype.cancel=function(){this.kb=!0;K$o(this)};var C$o=function(a){a.Sb=Date.now()+a.pba;R$o(a,a.pba)},R$o=function(a,b){if(a.Ta!=null)throw Error("kt");a.Ta=c$o((0,_.xe)(a.xc,a),b)},G$o=function(a){a.Ta&&(_.ca.clearTimeout(a.Ta),a.Ta=null)};f$o.prototype.xc=function(){this.Ta=null;const a=Date.now();a-this.Sb>=0?(w$o(this.Aa,this.Ha),this.zE!=2&&(Y9o(3),$9o(17)),K$o(this),this.hga=2,L$o(this)):R$o(this,this.Sb-a)};
var L$o=function(a){a.Ca.hv()||a.kb||N$o(a.Ca,a)},K$o=function(a){G$o(a);_.Pd(a.Bb);a.Bb=null;a.Yo.removeAll();if(a.oa){const b=a.oa;a.oa=null;b.abort();b.dispose()}};f$o.prototype.getLastError=function(){return this.hga};
var J$o=function(a,b){try{var c=a.Ca;if(c.Xe!=0&&(c.Aa==a||S$o(c.Ca,a)))if(!a.ob&&S$o(c.Ca,a)&&c.Xe==3){try{var d=c.vD.oa.parse(b)}catch(n){d=null}if(Array.isArray(d)&&d.length==3){var e=d;if(e[0]==0)a:if(c.oa.debug("Server claims our backchannel is missing."),c.Ma)c.oa.debug("But we are currently starting the request.");else{if(c.Aa)if(c.Aa.Va+3E3<a.Va)T$o(c),U$o(c);else break a;V$o(c);$9o(18)}else{c.ze=e[1];var f=c.ze-c.Bb;if(0<f){var g=e[2];c.oa.debug(g+" bytes (in "+f+" arrays) are outstanding on the BackChannel");
g<37500&&c.Za&&c.Pa==0&&!c.Na&&(c.Na=c$o((0,_.xe)(c.Dh,c),6E3))}}if(W$o(c.Ca)<=1&&c.Fp){try{c.Fp()}catch(n){}c.Fp=void 0}}else c.oa.debug("Bad POST response data returned"),X$o(c,11)}else if((a.ob||c.Aa==a)&&T$o(c),!_.ha(b))for(e=c.vD.oa.parse(b),f=0;f<e.length;f++){let n=e[f];const q=n[0];if(!(q<=c.Bb))if(c.Bb=q,n=n[1],c.Xe==2)if(n[0]=="c"){c.Gb=n[1];c.ld=n[2];const r=n[3];r!=null&&(c.Lc=r,c.oa.info("VER="+c.Lc));const u=n[4];u!=null&&(c.Ef=u,c.oa.info("SVER="+c.Ef));const A=n[5];A!=null&&typeof A===
"number"&&A>0&&(g=1.5*A,c.Lb=g,c.oa.info("backChannelRequestTimeoutMs_="+g));g=c;const G=a.oa;if(G){const N=_.bWb(G,"X-Client-Wire-Protocol");if(N){var h=g.Ca;b=N;!h.oa&&(_.ia(b,"spdy")||_.ia(b,"quic")||_.ia(b,"h2"))&&(h.Ba=h.Ca,h.oa=new Set,h.Bo&&(Y$o(h,h.Bo),h.Bo=null))}if(g.Va){const T=_.bWb(G,"X-HTTP-Session-Id");T&&(g.Kd=T,_.Jn(g.ob,g.Va,T))}}c.Xe=3;c.Da&&c.Da.F3c();c.Nc&&(c.Xb=Date.now()-a.Va,c.oa.info("Handshake RTT: "+c.Xb+"ms"));g=c;b=a;var k=d=g;const L=Z$o(k,k.Cb?g.ld:null,g.wc);k.oa.debug("GetBackChannelUri: "+
L);d.Id=L;if(b.ob){g.oa.debug("Upgrade the handshake request to a backchannel.");$$o(g.Ca,b);d=b;var l=g.Lb;l&&d.setTimeout(l);d.Ta&&(G$o(d),C$o(d));g.Aa=b}else aap(g);c.Ba.length>0&&bap(c)}else n[0]!="stop"&&n[0]!="close"||X$o(c,7);else c.Xe==3&&(n[0]=="stop"||n[0]=="close"?n[0]=="stop"?X$o(c,7):c.disconnect():n[0]!="noop"&&c.Da&&c.Da.y9c(n),c.Pa=0)}Y9o(4)}catch(n){}};var cap=class{constructor(a,b){this.mapId=a;this.map=b;this.context=null}};var m$o=function(a){this.Ca=a||10;_.ca.PerformanceNavigationTiming?(a=_.ca.performance.getEntriesByType("navigation"),a=a.length>0&&(a[0].nextHopProtocol=="hq"||a[0].nextHopProtocol=="h2")):a=!!(_.ca.chrome&&_.ca.chrome.loadTimes&&_.ca.chrome.loadTimes()&&_.ca.chrome.loadTimes().wasFetchedViaSpdy);this.Ba=a?this.Ca:1;this.oa=null;this.Ba>1&&(this.oa=new Set);this.Bo=null;this.Aa=[]},dap=function(a){return a.Bo?!0:a.oa?a.oa.size>=a.Ba:!1},W$o=function(a){return a.Bo?1:a.oa?a.oa.size:0},S$o=function(a,
b){return a.Bo?a.Bo==b:a.oa?a.oa.has(b):!1},Y$o=function(a,b){a.oa?a.oa.add(b):a.Bo=b},$$o=function(a,b){a.Bo&&a.Bo==b?a.Bo=null:a.oa&&a.oa.has(b)&&a.oa.delete(b)};m$o.prototype.cancel=function(){this.Aa=eap(this);if(this.Bo)this.Bo.cancel(),this.Bo=null;else if(this.oa&&this.oa.size!==0){for(const a of this.oa.values())a.cancel();this.oa.clear()}};
var eap=function(a){if(a.Bo!=null)return a.Aa.concat(a.Bo.Ua);if(a.oa!=null&&a.oa.size!==0){let b=a.Aa;for(const c of a.oa.values())b=b.concat(c.Ua);return b}return _.Ba(a.Aa)},fap=function(a,b){a.Aa=a.Aa.concat(b)};var j$o=class{stringify(a){return _.ca.JSON.stringify(a,void 0)}parse(a){return _.ca.JSON.parse(a,void 0)}};n$o.prototype.Lc=8;n$o.prototype.Xe=1;n$o.prototype.connect=function(a,b,c,d){this.oa.debug("connect()");$9o(0);this.wc=a;this.kb=b||{};c&&d!==void 0&&(this.kb.OSID=c,this.kb.OAID=d);this.Za=this.Bc;this.oa.debug("connectChannel_()");a=Z$o(this,null,this.wc);this.oa.debug("GetForwardChannelUri: "+a);this.ob=a;bap(this)};
n$o.prototype.disconnect=function(){this.oa.debug("disconnect()");gap(this);if(this.Xe==3){var a=this.xc++,b=this.ob.clone();_.Jn(b,"SID",this.Gb);_.Jn(b,"RID",a);_.Jn(b,"TYPE","terminate");hap(this,b);a=new f$o(this,this.oa,a);a.zE=2;a.Pa=_.PLa(b.clone());b=!1;if(_.ca.navigator&&_.ca.navigator.sendBeacon)try{b=_.ca.navigator.sendBeacon(a.Pa.toString(),"")}catch(c){}!b&&_.ca.Image&&((new Image).src=a.Pa,b=!0);b||(a.oa=D$o(a.Ca,null),a.oa.send(a.Pa));a.Va=Date.now();C$o(a)}iap(this)};
var U$o=function(a){a.Aa&&(Q$o(a),a.Aa.cancel(),a.Aa=null)},gap=function(a){U$o(a);a.Ma&&(_.ca.clearTimeout(a.Ma),a.Ma=null);T$o(a);a.Ca.cancel();a.Ea&&(typeof a.Ea==="number"&&_.ca.clearTimeout(a.Ea),a.Ea=null)};n$o.prototype.hv=function(){return this.Xe==0};n$o.prototype.getState=function(){return this.Xe};
var bap=function(a){dap(a.Ca)||a.Ea||(a.Ea=!0,_.oKa(a.Ue,a),a.Ua=0)},kap=function(a,b){if(W$o(a.Ca)>=a.Ca.Ba-(a.Ea?1:0))return!1;if(a.Ea)return a.oa.debug("Use the retry request that is already scheduled."),a.Ba=b.Ua.concat(a.Ba),!0;if(a.Xe==1||a.Xe==2||a.Ua>=(a.Lf?0:a.Mf))return!1;a.oa.debug("Going to retry POST");a.Ea=c$o((0,_.xe)(a.Ue,a,b),jap(a,a.Ua));a.Ua++;return!0};
n$o.prototype.Ue=function(a){if(this.Ea)if(this.Ea=null,this.oa.debug("startForwardChannel_"),this.Xe==1){if(!a){this.oa.debug("open_()");this.xc=Math.floor(Math.random()*1E5);a=this.xc++;const e=new f$o(this,this.oa,a);let f=this.Ka;this.qc&&(f?(f=_.Kc(f),_.Mc(f,this.qc)):f=this.qc);this.Ha!==null||this.Sb||(e.Za=f,f=null);if(this.Vb)a:{var b=0;for(var c=0;c<this.Ba.length;c++){b:{var d=this.Ba[c];if("__data__"in d.map&&(d=d.map.__data__,typeof d==="string")){d=d.length;break b}d=void 0}if(d===void 0)break;
b+=d;if(b>4096){b=c;break a}if(b===4096||c===this.Ba.length-1){b=c+1;break a}}b=this.fw}else b=this.fw;b=lap(this,e,b);c=this.ob.clone();_.Jn(c,"RID",a);_.Jn(c,"CVER",22);this.Va&&_.Jn(c,"X-HTTP-Session-Id",this.Va);hap(this,c);f&&(this.Sb?b="headers="+_.pd(_.hWb(f))+"&"+b:this.Ha&&_.iWb(c,this.Ha,f));Y$o(this.Ca,e);this.Hg&&_.Jn(c,"TYPE","init");this.Vb?(_.Jn(c,"$req",b),_.Jn(c,"SID","null"),e.Rb=!0,B$o(e,c,null)):B$o(e,c,b);this.Xe=2}}else this.Xe==3&&(a?map(this,a):this.Ba.length==0?this.oa.debug("startForwardChannel_ returned: nothing to send"):
dap(this.Ca)||(map(this),this.oa.debug("startForwardChannel_ finished, sent request")))};
var map=function(a,b){var c;b?c=b.Da:c=a.xc++;const d=a.ob.clone();_.Jn(d,"SID",a.Gb);_.Jn(d,"RID",c);_.Jn(d,"AID",a.Bb);hap(a,d);a.Ha&&a.Ka&&_.iWb(d,a.Ha,a.Ka);c=new f$o(a,a.oa,c,a.Ua+1);a.Ha===null&&(c.Za=a.Ka);b&&(a.Ba=b.Ua.concat(a.Ba));b=lap(a,c,a.fw);c.setTimeout(Math.round(a.Od*.5)+Math.round(a.Od*.5*Math.random()));Y$o(a.Ca,c);B$o(c,d,b)},hap=function(a,b){a.kb&&_.Dc(a.kb,function(c,d){_.Jn(b,d,c)});a.Da&&_.Dc({},function(c,d){_.Jn(b,d,c)})},lap=function(a,b,c){c=Math.min(a.Ba.length,c);const d=
a.Da?(0,_.xe)(a.Da.Q0d,a.Da,a):null;a:{var e=a.Ba;let h=-1;for(;;){const k=["count="+c];h==-1?c>0?(h=e[0].mapId,k.push("ofs="+h)):h=0:k.push("ofs="+h);let l=!0;for(let n=0;n<c;n++){var f=e[n].mapId;const q=e[n].map;f-=h;if(f<0)h=Math.max(0,e[n].mapId-100),l=!1;else try{f="req"+f+"_"||"";try{var g=q instanceof Map?q:Object.entries(q);for(const [r,u]of g){let A=u;_.Yf(u)&&(A=_.rNa(u));k.push(f+r+"="+encodeURIComponent(A))}}catch(r){throw k.push(f+"type="+encodeURIComponent("_badmap")),r;}}catch(r){d&&
d(q)}}if(l){g=k.join("&");break a}}g=void 0}a=a.Ba.splice(0,c);b.Ua=a;return g},aap=function(a){a.Aa||a.Ma||(a.Mc=1,_.oKa(a.Le,a),a.Pa=0)},V$o=function(a){if(a.Aa||a.Ma||a.Pa>=3)return!1;a.oa.debug("Going to retry GET");a.Mc++;a.Ma=c$o((0,_.xe)(a.Le,a),jap(a,a.Pa));a.Pa++;return!0};n$o.prototype.Le=function(){this.Ma=null;nap(this);if(this.Nc&&!(this.Nb||this.Aa==null||this.Xb<=0)){var a=4*this.Xb;this.oa.info("BP detection timer enabled: "+a);this.Ta=c$o((0,_.xe)(this.Yh,this),a)}};
n$o.prototype.Yh=function(){this.Ta&&(this.Ta=null,this.oa.info("BP detection timeout reached."),this.Aa.oa!=null&&this.Aa.oa.AA(),this.oa.info("Buffering proxy detected and switch to long-polling!"),this.Za=!1,this.Nb=!0,$9o(10),U$o(this),nap(this))};
var Q$o=function(a){a.Ta!=null&&(a.oa.debug("Cancel the BP detection timer."),_.ca.clearTimeout(a.Ta),a.Ta=null)},nap=function(a){a.oa.debug("Creating new HttpRequest");a.Aa=new f$o(a,a.oa,"rpc",a.Mc);a.Ha===null&&(a.Aa.Za=a.Ka);a.Aa.Cb=0;var b=a.Id.clone();_.Jn(b,"RID","rpc");_.Jn(b,"SID",a.Gb);_.Jn(b,"AID",a.Bb);_.Jn(b,"CI",a.Za?"0":"1");!a.Za&&a.Cd&&_.Jn(b,"TO",a.Cd);_.Jn(b,"TYPE","xmlhttp");hap(a,b);a.Ha&&a.Ka&&_.iWb(b,a.Ha,a.Ka);a.Lb&&a.Aa.setTimeout(a.Lb);var c=a.Aa,d=a.ld;c.zE=1;c.Pa=_.PLa(b.clone());
c.Ea=null;c.Gb=!0;A$o(c,d);a.oa.debug("New Request created")};n$o.prototype.Dh=function(){this.Na!=null&&(this.Na=null,U$o(this),V$o(this),$9o(19))};
var T$o=function(a){a.Na!=null&&(_.ca.clearTimeout(a.Na),a.Na=null)},N$o=function(a,b){a.oa.debug("Request complete");let c,d=null;if(a.Aa==b)T$o(a),Q$o(a),a.Aa=null,c=2;else if(S$o(a.Ca,b))d=b.Ua,$$o(a.Ca,b),c=1;else return;if(a.Xe!=0)if(b.Ka)c==1?(b$o(b.Ea?b.Ea.length:0,Date.now()-b.Va,a.Ua),bap(a)):aap(a);else{var e=b.Lb,f=b.getLastError();if(f==3||f==0&&e>0)a.oa.debug("Not retrying due to error type"),e>200&&(a.Rb=b.Lb);else{a.oa.debug(function(){return"Maybe retrying, last error: "+x$o(f,a.Rb)});
if(c==1&&kap(a,b)||c==2&&V$o(a))return;a.oa.debug("Exceeded max number of retries")}d&&d.length>0&&fap(a.Ca,d);a.oa.debug("Error: HTTP request failed");switch(f){case 1:X$o(a,5);break;case 4:X$o(a,10);break;case 3:X$o(a,6);break;default:X$o(a,2)}}},jap=function(a,b){let c=a.tF+Math.floor(Math.random()*a.Mha);a.isActive()||(a.oa.debug("Inactive channel"),c*=2);return c*b},X$o=function(a,b){a.oa.info("Error code "+b);if(b==2){var c=(0,_.xe)(a.Dk,a),d=a.Kg;const e=!d;d=new _.Dn(d||"//www.google.com/images/cleardot.gif");
_.ca.location&&_.ca.location.protocol=="http"||_.En(d,"https");_.PLa(d);e?h$o(d.toString(),c):i$o(d.toString(),c)}else $9o(2);a.oa.debug("HttpChannel: error - "+b);a.Xe=0;a.Da&&a.Da.x9c(b);iap(a);gap(a)};n$o.prototype.Dk=function(a){a?(this.oa.info("Successfully pinged google.com"),$9o(2)):(this.oa.info("Failed to ping google.com"),$9o(1))};
var iap=function(a){a.Xe=0;a.vd=[];if(a.Da){const b=eap(a.Ca);if(b.length!=0||a.Ba.length!=0)a.oa.debug(()=>"Number of undelivered maps, pending: "+b.length+", outgoing: "+a.Ba.length),_.Ea(a.vd,b),_.Ea(a.vd,a.Ba),a.Ca.Aa.length=0,_.Ba(a.Ba),a.Ba.length=0;a.Da.w9c()}},Z$o=function(a,b,c){var d=_.xh(c);d.uw()!=""?(b&&_.Fn(d,b+"."+d.uw()),_.Gn(d,d.Ca)):(d=_.ca.location,d=_.RLa(d.protocol,null,b?b+"."+d.hostname:d.hostname,+d.port,c));b=a.Va;c=a.Kd;b&&c&&_.Jn(d,b,c);_.Jn(d,"VER",a.Lc);hap(a,d);return d},
D$o=function(a,b,c){if(b&&!a.Cb)throw Error("lt");b=a.Sf&&!a.L0b?new _.qr(new _.cWb({TGd:c})):new _.qr(a.L0b);b.setWithCredentials(a.Cb);return b};n$o.prototype.isActive=function(){return!!this.Da&&this.Da.isActive(this)};var oap=function(){};_.aa=oap.prototype;_.aa.F3c=function(){};_.aa.y9c=function(){};_.aa.x9c=function(){};_.aa.w9c=function(){};_.aa.isActive=function(){return!0};_.aa.Q0d=function(){};var pap;_.qap=function(a,b,c){return new pap(b,c)};
pap=function(a,b){_.ue.call(this);this.oa=new n$o(b);this.Ca=a;this.Vm=null;this.Aa=b&&b.Uue||null;a=b&&b.Tue||null;b&&b.KMf&&(a?a["X-Client-Protocol"]="webchannel":a={"X-Client-Protocol":"webchannel"});this.oa.Ka=a;a=b&&b.xnd||null;b&&b.Mec&&(a?a["X-WebChannel-Content-Type"]=b.Mec:a={"X-WebChannel-Content-Type":b.Mec});b&&b.a$c&&(a?a["X-WebChannel-Client-Profile"]=b.a$c:a={"X-WebChannel-Client-Profile":b.a$c});this.oa.qc=a;(a=b&&b.qmd)&&!_.ha(a)&&(this.oa.Ha=a);this.Ea=b&&b.fYc||!1;this.Da=b&&b.jVc||
!1;(b=b&&b.uHc)&&!_.ha(b)&&(this.oa.Va=b,_.zka(this.Aa,b)&&_.Bka(this.Aa,b));this.Ba=new rap(this)};_.vi(pap,_.ue);_.aa=pap.prototype;_.aa.open=function(){this.oa.Da=this.Ba;this.Ea&&(this.oa.Cb=!0);this.oa.connect(this.Ca,this.Aa||void 0)};_.aa.close=function(){this.oa.disconnect()};_.aa.halfClose=function(){throw Error("Ya");};_.aa.send=function(a){var b=this.oa;if(typeof a==="string"){var c={};c.__data__=a;a=c}else this.Da&&(c={},c.__data__=_.rNa(a),a=c);b.Ba.push(new cap(b.Di++,a));b.Xe==3&&bap(b)};
_.aa.Vc=function(){this.oa.Da=null;delete this.Ba;this.oa.disconnect();delete this.oa;pap.Af.Vc.call(this)};var sap=function(a){q$o.call(this);a.__headers__&&(this.headers=a.__headers__,this.statusCode=a.__status__,delete a.__headers__,delete a.__status__);const b=a.__sm__;if(b){a:{for(const c in b){a=c;break a}a=void 0}this.data=(this.oa=a)?_.Cka(b,this.oa):b}else this.data=a};_.vi(sap,q$o);var tap=function(a){r$o.call(this);this.status=1;this.errorCode=a};_.vi(tap,r$o);
var rap=function(a){this.oa=a};_.vi(rap,oap);rap.prototype.F3c=function(){this.oa.dispatchEvent("u")};rap.prototype.y9c=function(a){this.oa.dispatchEvent(new sap(a))};rap.prototype.x9c=function(a){this.oa.dispatchEvent(new tap(a))};rap.prototype.w9c=function(){this.oa.dispatchEvent("v")};
var ooi,qoi,roi,soi,voi,woi,xoi;ooi=function(){return""};_.poi=function(){return(_.zH?"z1asCe ":"")+(_.zH?"wuXmqc ":"")+(_.zH?"":"WqQeqc ")+(_.zH?"":"FAgkbc ")};qoi=function(){return""};roi=function(){return!0};soi=function(){return!1};voi=function(a,b){_.toi(a);return _.uoi(a,b.Ob,b.Pb)};woi=function(a,b){_.toi(a);var c=b.Ob,d=b.Pb;b="<span"+_.W(_.poi(a,c,d)+"")+_.Y("")+_.V("")+">";a=_.uoi(a,c,d);return _.w(b+(a+"</span>"))};
_.uoi=function(a,b,c){b=b==null?null:b;c=c==null?null:c;c=(b!=null?_.DM(a,b):"")+(c!=null?_.DM(a,c):"")+(_.zH?(_.CH==0?"<svg"+_.W("")+_.Y("")+_.V(' focusable="false" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"')+"><path"+_.W("")+_.Y("")+_.V(' d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"')+"></path></svg>":"")+(_.CH==1?"<svg"+_.W("")+_.Y("")+_.V(' focusable="false" aria-hidden="true" viewBox="0 0 24 24"')+"><path"+
_.W("")+_.Y("")+_.V(' d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"')+"></path></svg>":""):"");_.zH||(a.Ba(_.AH?".FAgkbc span{"+_.CB("mask-image",1)+":url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAk0lEQVR4Ae2W1w3DQAzFHnBD3oCpO6a4D8CD8FzFb4lM3JWcmCQpuquKUofp0qZ/q9NXFeq/6vRuSdzVqQOJRb9M35l8WQIJPMkX43q+zPU8EdcjSVwPREAfSAB9JBHUg0RIDxIe/ZIw6L0B/yHyn2T/Zeq/0fijwv+w8z+u/S8c/yvT/9L3f7b4P7z8n45JkpyQHoZ1C+CAch8WAAAAAElFTkSuQmCC)}":
""),a.Ba(_.AH?"":".FAgkbc span{background-image:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAk0lEQVR4Ae2W1w3DQAzFHnBD3oCpO6a4D8CD8FzFb4lM3JWcmCQpuquKUofp0qZ/q9NXFeq/6vRuSdzVqQOJRb9M35l8WQIJPMkX43q+zPU8EdcjSVwPREAfSAB9JBHUg0RIDxIe/ZIw6L0B/yHyn2T/Zeq/0fijwv+w8z+u/S8c/yvT/9L3f7b4P7z8n45JkpyQHoZ1C+CAch8WAAAAAElFTkSuQmCC)}"),c+="<span"+_.W("")+_.Y("")+_.V("")+"></span>");return c};_.toi=function(a){a.oa(xoi)||a.Aa(xoi,{Ob:0,Pb:1},voi,woi,roi,soi,"",ooi,"",_.poi,"",qoi)};
xoi="t-djdyZmG6MyA";
var yoi,zoi,Aoi,Boi,Coi,Doi;yoi=function(){return""};_.TS=function(a,b,c,d){return""+_.poi(a,c==null?null:c,d==null?null:d)};_.US=function(a,b){var c=b!=24;return(c?"height:"+_.R(_.jB(a.isRtl()?_.fB("height",String(b)+"px"):String(b)+"px"))+";":"")+(c?"line-height:"+_.R(_.jB(a.isRtl()?_.fB("line-height",String(b)+"px"):String(b)+"px"))+";":"")+(c?"width:"+_.R(_.jB(a.isRtl()?_.fB("width",String(b)+"px"):String(b)+"px"))+";":"")};zoi=function(){return!0};Aoi=function(){return!1};
Boi=function(a,b){_.VS(a);return _.WS(a,b.Ob,b.Pb)};Coi=function(a,b){_.VS(a);var c=b.size,d=b.Ob,e=b.Pb;b="";c="<span"+_.W(_.TS(a,c,d,e)+"")+_.Y(_.US(a,c,d,e)+"")+_.V("")+">";a=_.WS(a,d,e);b+=c+(a+"</span>");return _.w(b)};_.WS=function(a,b,c){return _.uoi(a,b==null?null:b,c==null?null:c)};_.VS=function(a){a.oa(Doi)||(a.Aa(Doi,{size:0,Ob:1,Pb:2},Boi,Coi,zoi,Aoi,"",yoi,"",_.TS,"",_.US),_.toi(a))};Doi="t-PiqLEHKTC3M";
_.t("spch");
var EKE=function(){if(CKE){var a=.5+Math.random()*.55,b=Math.round(170+Math.random()*10);DKE.style.setProperty("-webkit-transition",`${"-webkit-transform"} ${b/1E3}s ease-in-out`);DKE.style.setProperty("-webkit-transform","scale("+a+")");window.setTimeout(EKE,b)}else DKE.style.removeProperty("opacity"),DKE.style.removeProperty("-webkit-transition"),DKE.style.removeProperty("-webkit-transform")},KKE=function(){window.clearTimeout(FKE);window.clearTimeout(GKE);HKE=0;_.Yl.set(IKE,"z5vYxf");_.Yl.set(JKE,
"z5vYxf")},NKE=function(){LKE=MKE;JKE=_.bm("KHjmsf");IKE=_.bm("yZ04Ef");KKE();return!(!JKE||!IKE)},OKE=function(a,b,c){window.clearTimeout(GKE);window.clearTimeout(FKE);c?(_.Zc(IKE,_.wc(a)),_.Zc(JKE,_.wc(b)),a=IKE.firstElementChild,a.id="spchta",_.zm(a,!0),_.Yl.set(a,"cb7x7d")):(IKE.textContent=a,JKE.textContent=b);a=IKE;b=JKE;HKE===0&&(HKE=LKE?28:27);c=1.2*HKE+1;const d=1.2*HKE*2+1,e=1.2*HKE*3+1;a.className=b.className=IKE.scrollHeight>1.2*HKE*4+1?"z5vYxf qi9U9e":IKE.scrollHeight>e?"z5vYxf hAjVCb":
IKE.scrollHeight>d?"z5vYxf ZZaLcf":IKE.scrollHeight>c?"z5vYxf hcf8eb":"z5vYxf"},QKE=function(){function a(){const d=PKE.Pja,e=b>0&&IKE.textContent!==d.substring(0,b),f=b===0&&IKE.textContent!==PKE.ready;b===d.length||e||f||(c+=d.substring(b,b+1),OKE(c,""),++b,FKE=window.setTimeout(a,30))}let b=0,c="";FKE=window.setTimeout(a,2E3)},RKE=function(){IKE.textContent="";JKE.textContent="";GKE=window.setTimeout(function(){IKE.textContent===""&&OKE(PKE.waiting,"")},300)},VKE=function(){SKE=_.am("spch-dlg");
TKE=_.am("spch");UKE=_.am("spchc")},XKE=function(){MKE||MKE||(CKE=!1);WKE&&_.Yl.set(UKE,"spchc OJaju")},ZKE=function(a){WKE&&MKE&&a!=="vso"&&YKE()},eLE=function(a,b){var c=$KE,d=aLE;MKE=a;bLE=b;VKE();cLE=c;a&&d&&(YKE=d,_.gg("fpstate",ZKE));(a=(bLE?!!SKE:!0)&&!!TKE&&!!UKE&&!!NKE())&&!(a=MKE)&&(dLE=_.am("spchb"),DKE=_.am("spchl"),a=!(!dLE||!DKE));return a},gLE=function(a){_.Yl.set(UKE,"spchc s2er");switch(a){case "8":OKE(PKE.xvd,"",!0);break;case "0":OKE(PKE.yvd,"",!0);break;case "2":OKE(PKE.I7c,"",
!0);break;case "3":OKE(PKE.hvd,"");break;case "4":case "5":OKE(PKE.cyd,"",!0);break;case "7":OKE(PKE.wrd,"")}MKE||(CKE=!1);a==="8"&&(fLE=!0)},iLE=function(a){if(WKE){a=(a==null?void 0:a.target).id;var b="";a==="spchx"?hLE="0":a==="spch"?hLE="2":a==="spchb"?hLE="1":a==="spchta"?hLE="5":b=a;cLE(hLE,b,hLE==="1"&&!fLE,(hLE==="1"||hLE==="5")&&fLE)}},jLE=function(){window.removeEventListener("mouseup",iLE,!1);MKE&&_.og("fpstate")&&_.ng();(bLE||MKE)&&SKE.close();_.Yl.set(TKE,"spch");_.Yl.set(UKE,"spchc");
TKE.removeAttribute("style");_.Xm(TKE,!1);fLE=WKE=!1;KKE()},kLE=function(a){switch(a){case "no-speech":return["0",8E3];case "aborted":return["1",3E3];case "audio-capture":return["2",8E3];case "network":return["3",3E3];case "not-allowed":return["4",8E3];case "service-not-allowed":return["5",8E3];case "bad-grammar":return["6",3E3];case "language-not-supported":return["7",3E3];default:return["9",3E3]}},mLE=function(a){for(const b of[0,1,2]){let c;const d=(c=_.lLE.get(b))==null?void 0:c(a);if(d)return d}},
rLE=function(){D7=-1;_.G0(_.H0.zqc);_.Hg(document.body,"CQJmec");_.ln(window,"keydown",nLE);_.e_q(_.H0.H1b,oLE);pLE&&(_.Ag(pLE),pLE=null);_.e_q(_.H0.Z3c,oLE);_.e_q(_.H0.Y3c,qLE)},uLE=function(a,b){D7!==7&&_.G0(_.H0.NSd);D7===10&&(D7=11,sLE.stop());a==null||a<=0?(XKE(),jLE(),b(),tLE()):(XKE(),_.Th(a).then(()=>{jLE();b();tLE()}))},vLE=function(){uLE(0,()=>{})},xLE=function(a,b,c){wLE(a,b,c);D7=10;vLE()},tLE=function(){window.clearTimeout(yLE);window.clearTimeout(zLE);window.clearTimeout(ALE);_.G0(_.H0.Aqc);
_.Hg(document.body,"hATt5e");_.ln(_.jf(),"visibilitychange",BLE,!1);CLE="";D7=0;sLE.stop()},ELE=function(){DLE(8E3);window.clearTimeout(ALE);D7=4;WKE&&(_.Yl.set(UKE,"spchc s2ml"),window.clearTimeout(GKE),OKE(PKE.ready,""),QKE())},FLE=function(){DLE(8E3);D7=5;WKE&&(_.Yl.set(UKE,"spchc s2ra"),bLE||MKE||TKE.classList.add("t2n14d"),MKE||CKE||(CKE=!0,EKE()),window.clearTimeout(FKE))},HLE=function(a,b,c){DLE(8E3);switch(D7){case 6:case 5:break;case 4:FLE();break;case 3:FLE();ELE();break;default:return}D7=
6;WKE&&(_.Yl.set(UKE,"spchc s2ra"),OKE(a,b));CLE=b;b=a.length>120;c||b?GLE(18):(_.G0(_.H0.PSd,[a]),_.Hg(document.body,"u9RZBc",a))},JLE=function(a,b,c){DLE(8E3);window.clearTimeout(ALE);a!=="1"&&(wLE(2,a,a==="9"?b:""),D7=8,gLE(a),window.clearTimeout(yLE),ILE(c))},KLE=function(){wLE(4);D7=8;gLE("8");window.clearTimeout(yLE);ILE(8E3)},LLE=function(){window.clearTimeout(yLE);window.clearTimeout(ALE);let a="9";switch(D7){case 3:D7=9;a="2";break;case 4:D7=9;a="0";break;case 5:case 6:D7=9;a="8";break;case 8:break;
default:return}switch(D7){case 9:gLE(a);ILE(8E3);wLE(3,a);D7=11;break;case 8:D7=11;break;default:D7=11,vLE()}},nLE=function(a){if(MLE()&&D7!==-1){var b=a.ctrlKey||_.PBa&&a.metaKey;D7===0&&a.keyCode===190&&a.shiftKey&&b&&oLE()}else if(a.stopPropagation(),a.keyCode===27)xLE(0,"0");else if(b=a.keyCode,b===13||b===32){if(b=a.target!=null)b=a.target.id,b=b==="spchta"||b==="spchx";b?iLE(a.Gg):CLE&&GLE(3)}},NLE=function(){if(CLE!=="")GLE(19);else switch(D7){case 3:case 4:case 5:case 6:case 8:xLE(0,"3")}},
OLE=function(){DLE(15E3);wLE(0,"6");WKE&&_.Yl.set(UKE,"spchc s2wfp")},BLE=function(){MLE()||_.jf().isHidden()&&xLE(0,"4")},qLE=function(){MLE()||xLE(0,"7")},GLE=function(a){D7=7;window.clearTimeout(yLE);const b=CLE;b!==""&&uLE(a===18?PLE:0,()=>{_.G0(_.H0.yqc,[b,a]);_.Hg(document.body,"KHxBOb",[b,a])})},wLE=function(a,b,c){let d="";b&&(d+=`&reason=${b}`);c&&(d+=`&data=${c}`);google.log("spch-recog",a+d)},DLE=function(a){window.clearTimeout(yLE);yLE=window.setTimeout(NLE,a)},ILE=function(a){window.clearTimeout(zLE);
zLE=window.setTimeout(()=>{vLE()},a)},MLE=function(){switch(D7){case 0:case -1:case 1:return!0}return!1},oLE=function(){const a=_.am("spch");a&&_.Tf(a,"clicked");if(D7===-1)wLE(5);else if(D7!==0)xLE(0,"5");else if(D7=2,sLE&&D7===2){WKE||(VKE(),NKE(),RKE(),WKE||(_.Xm(TKE,!0),MKE&&_.kg("fpstate","vso"),(MKE||bLE)&&SKE.showModal(),_.Yl.set(TKE,"spch"),_.Yl.set(TKE,"spch YFwiVb"),WKE=!0),window.addEventListener("mouseup",iLE,!1));DLE(8E3);window.clearTimeout(ALE);ALE=window.setTimeout(OLE,1500);_.G0(_.H0.OSd);
_.we(_.jf(),"visibilitychange",BLE,!1);sLE&&sLE.isInitialized()||sLE.initialize();try{sLE.start(),D7=3}catch(b){D7=2;sLE.initialize();try{sLE.start(),D7=3}catch(c){D7=10,wLE(0,"1"),vLE()}}}},$KE=function(a,b,c,d){CLE&&c?GLE(17):D7===11&&d?(wLE(6,a,b),tLE(),oLE()):xLE(1,a,b)},aLE=function(){xLE(8,"8")},PKE={I7c:"",wrd:"",Pja:"",hvd:"",xvd:"",yvd:"",cyd:"",ready:"",waiting:""},dLE,DKE,CKE=!1,JKE,IKE,HKE,GKE,FKE,LKE,hLE="4",MKE=!1,bLE=!1,SKE,TKE,UKE,fLE=!1,WKE=!1,cLE,YKE,QLE=!!(_.qi[24]>>18&1),E7=!!(_.qi[24]>>
19&1);_.RLE=class{constructor(a){this.language="";this.flags={};this.listeningStartHandler=()=>{};this.speechStartHandler=()=>{};this.recognitionResultHandler=()=>{};this.recognitionEndHandler=()=>{};this.errorHandler=()=>{};this.noMatchHandler=()=>{};this.language=a.language||"en-US";this.flags=a.flags||{};this.listeningStartHandler=a.listeningStartHandler||this.listeningStartHandler;this.speechStartHandler=a.speechStartHandler||this.speechStartHandler;this.recognitionResultHandler=a.recognitionResultHandler||
this.recognitionResultHandler;this.recognitionEndHandler=a.recognitionEndHandler||this.recognitionEndHandler;this.errorHandler=a.errorHandler||this.errorHandler;this.noMatchHandler=a.noMatchHandler||this.noMatchHandler}};var SLE=class extends _.RLE{initialize(){this.oa=new window.webkitSpeechRecognition;this.oa.continuous=!1;this.oa.interimResults=!0;this.oa.lang=this.language;this.oa.maxAlternatives=4;this.oa.onerror=this.Aa.bind(this);this.oa.onnomatch=this.noMatchHandler;this.oa.onend=this.recognitionEndHandler;this.oa.onresult=this.Ba.bind(this);this.oa.onaudiostart=this.listeningStartHandler;this.oa.onspeechstart=this.speechStartHandler}isInitialized(){return!!this.oa}start(){this.oa.start()}stop(){this.oa.abort()}Ba(a){const b=
a.results,c=b.length;if(c!==0){var d="",e="",f=a.resultIndex;if(a=b[f].isFinal)d=e=b[f][0].transcript;else for(f=0;f<c;f++){const g=b[f][0].transcript;d+=g;b[f][0].confidence>.5&&(e+=g)}this.recognitionResultHandler(d,e,a)}}Aa(a){const [b,c]=kLE(a.error);this.errorHandler(b,a.error,c)}};_.lLE=new Map([[2,function(a){if(window.webkitSpeechRecognition)return new SLE(a)}]]);var TLE=function(){return""},ULE=function(){return""},VLE=function(){return""},WLE=function(){return!0},XLE=function(){return!1},$LE=function(a){YLE(a);return ZLE(a)},aME=function(a){YLE(a);var b="<style"+_.W("")+_.Y("")+_.V("")+">";a=ZLE(a);return _.w(b+(a+"</style>"))},ZLE=function(a){a.Ba(".permission-bar{margin-top:-100px;opacity:0;pointer-events:none;position:absolute;width:500px;transition:opacity 0.218s ease-in,margin-top .4s ease-in}");a.Ba(".s2wfp .permission-bar{margin-top:-300px;opacity:1;transition:opacity .5s ease-out 0.218s,margin-top 0.218s ease-out 0.218s}");
a.Ba(".permission-bar-gradient{box-shadow:0 1px 0px #4285f4;height:80px;left:0;margin:0;opacity:0;pointer-events:none;position:fixed;right:0;top:-80px;transition:opacity 0.218s,box-shadow 0.218s}");a.Ba(".s2wfp .permission-bar-gradient{box-shadow:0 1px 80px #4285f4;opacity:1;pointer-events:none;"+_.CB("animation",1)+":allow-alert .75s 0 infinite;"+_.CB("animation-direction",1)+":alternate;"+_.CB("animation-timing-function",1)+":ease-out;transition:opacity 0.218s,box-shadow 0.218s}");a.Ba("@-webkit-keyframes allow-alert {from{opacity:1}to{opacity:.35}}");
return""},YLE=function(a){a.oa(bME)||a.Aa(bME,{},$LE,aME,WLE,XLE,"",TLE,"",ULE,"",VLE)},bME="t-_wSOtLKeKkA";var cME=function(){return""},dME=function(){return""},eME=function(){return""},fME=function(){return!0},gME=function(){return!1},jME=function(a){hME(a);return iME(a)},kME=function(a){hME(a);var b="<div"+_.W("permission-bar ")+_.Y("")+_.V("")+">";a=iME(a);return _.w(b+(a+"</div>"))},iME=function(a){return ZLE(a)+"<div"+_.W("permission-bar-gradient ")+_.Y("")+_.V("")+"></div>"},hME=function(a){a.oa(lME)||(a.Aa(lME,{},jME,kME,fME,gME,"",cME,"permission-bar ",dME,"",eME),YLE(a))},lME="t-y4DJ78xmMWs";var mME=function(){return""},nME=function(){return""},oME=function(){return""},pME=function(){return!0},qME=function(){return!1},tME=function(a){rME(a);return sME()},uME=function(a){rME(a);return _.w(sME())},sME=function(){return"close"},rME=function(a){a.oa(vME)||a.Aa(vME,{},tME,uME,pME,qME,"",mME,"",nME,"",oME)},vME="t-2UBRBUtV38g";var yME=function(a){wME(a);return xME(a)},zME=function(a){wME(a);a=xME(a);return _.w(a)},xME=function(a){var b=_.fA(_.Yh().Ya);a.Ba(".spch-dlg{background:"+_.U(b,"",c=>_.EA(c))+";border:none}");a.Ba(".spch{background:"+(_.U(b,"",c=>c.kd())+";height:100%;left:0;opacity:0;overflow:hidden;position:fixed;text-align:left;top:0;visibility:hidden;width:100%;z-index:10000;transition:visibility 0s linear 0.218s,background-color 0.218s;"+(QLE||E7?"":"background:"+_.U(b,"",c=>_.EA(c))+";")+(_.Biv&&!E7?"min-width:684px":
"")+"}"));a.Ba(".YFwiVb.spch{opacity:1;transition-delay:0s;"+(E7&&QLE?"visibility:inherit;":"")+(QLE?"":"visibility:visible;")+(E7||QLE?"":"background:"+_.U(b,"",c=>_.EA(c)))+"}");a.Ba(".pz5bj{background:none;border:none;color:"+(_.U(b,"",c=>_.Jo(c))+";cursor:pointer;font-size:26px;right:0;line-height:15px;opacity:.6;margin:-1px -1px 0 0;padding:0 0 2px 0;height:48px;width:48px;position:absolute;top:0;z-index:10}"));a.Ba(".pz5bj:hover{opacity:.8}");a.Ba(".pz5bj:active{opacity:1}");a.Ba(".spchc{display:block;height:42px;pointer-events:none;"+
(E7?"margin:auto;position:relative;top:0;":"")+(QLE&&E7?"margin-top:312px;max-width:400px;padding:0 100px;":"")+(!QLE&&E7?"margin-top:312px;max-width:572px;min-width:534px;padding:0 223px":"")+"}");a.Ba(".inner-container{height:100%;opacity:.1;pointer-events:none;width:100%;transition:opacity .318s ease-in;"+(_.Biv&&!E7?"display:flex":"")+"}");a.Ba(".s2ml .inner-container,.s2ra .inner-container,.s2er .inner-container,.OJaju .inner-container{opacity:1;transition:opacity 0s}");return""},wME=function(a){a.oa(AME)||
a.Aa(AME,{},yME,zME)},AME="t-I44BHHE4hj0";var DME=function(a){BME(a);return CME(a)},EME=function(a){BME(a);var b="<style"+_.W("")+_.Y("")+_.V("")+">";a=CME(a);return _.w(b+(a+"</style>"))},CME=function(a){var b=_.fA(_.Yh().Ya),c=_.fA(_.Yh().Qb);b=_.U(b,"",d=>_.zA(d));a.Ba(".df8vVc{"+(_.Biv&&!E7?"flex:1;max-width:490px;min-width:300px;width:100%;":"")+"pointer-events:none;"+(E7?"position:absolute;":"")+(E7?"":"position:relative")+"}");a.Ba(".z5vYxf{font-weight:normal;line-height:1.2;opacity:0;pointer-events:none;position:absolute;text-align:left;"+
(_.CB("font-smoothing",1)+":antialiased;transition:opacity .1s ease-in,margin-left .5s ease-in,top 0s linear 0.218s;"+(E7?"left:-44px;top:-.2em;margin-left:44px;":"")+(!QLE&&E7?"font-size:32px;width:460px;":"")+(QLE&&E7?"font-size:28px;width:300px;":"")+(E7?"":"font-size:27px;left:7px;top:.2em;width:490px;margin-left:32px")+"}"));a.Ba(".YFwiVb .z5vYxf{margin-left:0;opacity:1;transition:opacity .5s ease-out,margin-left .5s ease-out}");a.Ba(".cb7x7d{color:"+b+";cursor:pointer;font-size:"+_.U(c,"",d=>
_.$A(d))+";font-weight:500;pointer-events:auto;text-decoration:underline}");a.Ba(".hcf8eb.z5vYxf,.ZZaLcf.z5vYxf,.hAjVCb.z5vYxf{transition:top 0.218s ease-out}");a.Ba(".hcf8eb.z5vYxf{top:-.6em}");a.Ba(".ZZaLcf.z5vYxf{top:-1.3em}");a.Ba(".hAjVCb.z5vYxf{top:-1.7em}");a.Ba(".YFwiVb .qi9U9e.z5vYxf{"+(E7?"top:-2.5em;":"")+(E7?"":"font-size:24px;top:-1.7em;transition:font-size 0.218s ease-out")+"}");return""},BME=function(a){a.oa(FME)||a.Aa(FME,{},DME,EME)},FME="t-MpB9j-pDA3U";var GME=function(){return""},HME=function(){return""},IME=function(){return""},JME=function(){return!0},KME=function(){return!1},NME=function(a,b){LME(a);return MME(a,b.gtd,b.Tld)},OME=function(a,b){LME(a);var c=b.gtd,d=b.Tld;b="<div"+_.W("df8vVc ")+_.Y("")+_.V("")+">";a=MME(a,c,d);return _.w(b+(a+"</div>"))},MME=function(a,b,c){return CME(a)+"<span"+_.W("z5vYxf ")+_.Y("color:"+_.R(_.jB(a.isRtl()?_.fB("color",b):b))+";")+_.V(' id="yZ04Ef"')+"></span><span"+_.W("z5vYxf ")+_.Y("color:"+_.R(_.jB(a.isRtl()?
_.fB("color",c):c))+";")+_.V(' id="KHjmsf"')+"></span>"},LME=function(a){a.oa(PME)||(a.Aa(PME,{gtd:0,Tld:1},NME,OME,JME,KME,"",GME,"df8vVc ",HME,"",IME),BME(a))},PME="t-QB6f6FXn-2c";var SME=function(){var a=new _.JB;QME(a);let b="";_.fA(_.Yh().Ya);const c=RME(a),d=a.Da();d!==""&&(b+=" <style>"+d+"</style>");b+=c;a.Ea();return _.w(b)},TME=function(){_.fA(_.Yh().Ya);return""},UME=function(){_.fA(_.Yh().Ya);return""},VME=function(){_.fA(_.Yh().Ya);return""},WME=function(){_.fA(_.Yh().Ya);return!0},XME=function(){_.fA(_.Yh().Ya);return!1},YME=function(a){QME(a);return RME(a)},ZME=function(a){QME(a);_.fA(_.Yh().Ya);a=RME(a);return _.w(a)},RME=function(a){var b=_.fA(_.Yh().Ya),c=_.U(b,
"",f=>_.Jo(f)),d=_.U(b,"",f=>_.wA(f));b=xME(a)+"<button"+_.W("pz5bj ")+_.Y("")+_.V(' id="spchx" aria-label="'+_.kB(sME())+'"')+">";var e="<span"+_.W(_.TS(a,16,null,null)+"")+_.Y(_.US(a,16,null,null)+"")+_.V("")+">"+_.WS(a,null,null)+"</span>";b=b+e+("</button><div"+_.W("spchc ")+_.Y("")+_.V(' id="spchc"')+"><div"+_.W("inner-container ")+_.Y("")+_.V("")+">");c="<div"+_.W("df8vVc ")+_.Y("")+_.V("")+">"+MME(a,c,d)+"</div>";b+=c;b+="</div>";a="<div"+_.W("permission-bar ")+_.Y("")+_.V("")+">"+iME(a)+"</div>";
b+=a;return b+"</div>"},QME=function(a){a.oa($ME)||(a.Aa($ME,{},YME,ZME,WME,XME,"",TME,"",UME,"",VME),hME(a),rME(a),wME(a),LME(a),_.VS(a))},$ME="t-axpif1G9qm0";var pLE=null,D7=-1,zLE,yLE,aNE,ALE,sLE,CLE,PLE=0;
_.fh("spch",{init:function(a){aNE=a.hl;const b=a.mb,c=a.fp;PLE=a.cd;const d=_.am("spch");sLE=mLE({language:aNE,flags:a,listeningStartHandler:ELE,speechStartHandler:FLE,recognitionResultHandler:HLE,recognitionEndHandler:LLE,errorHandler:JLE,noMatchHandler:KLE});var e;if(e=b)d?(_.Zc(d,SME()),e=!0):e=!1,e=!e;e?rLE():sLE&&eLE(b,c)?(D7===-1&&(_.we(window,"keydown",nLE),_.c_q(_.H0.H1b,()=>{oLE()}),pLE=_.Dg(document.body,"ydZCDf",()=>{oLE()}),_.b_q(_.H0.Z3c,oLE),_.b_q(_.H0.Y3c,qLE)),PKE={Pja:a.lm,ready:a.rm,
xvd:a.nt,waiting:a.iw,I7c:a.ae,hvd:a.ne,wrd:a.lu,cyd:a.pe,yvd:a.nv},D7=1,sLE.initialize(),tLE(),d&&_.Rf(d,"clicked")&&oLE()):rLE()}});
var bNE=function(a){switch(a){case "NO_SPEECH":return["0",8E3];case "ABORTED":return["1",3E3];case "AUDIO_ERROR":case "MEDIA_RECORDER_ERROR":return["2",8E3];case "OFFLINE":return["3",3E3];case "NO_MATCH":return["8",8E3];case "NO_MICROPHONE_PERMISSION":return["4",3E3];default:return["9",8E3]}};var eNE=function(a){a.channel=_.qap(0,a.endpoint,{qmd:"$httpHeaders",uHc:"gsessionid",jVc:!0,xnd:{"x-goog-api-key":a.apiKey}});a.channel.open();_.we(a.channel,"u",()=>{a.channel.send({config:{dialogStateIn:{languageCode:a.languageCode},deviceConfig:{deviceId:"example",deviceModelId:"example"},audioInConfig:{encoding:"LINEAR16",sampleRateHertz:16E3},audioOutConfig:{encoding:"MP3",sampleRateHertz:22050,volumePercentage:0},requestType:4}});a.Ba=!0});_.we(a.channel,"v",()=>{a.Ba=!1;a.channel=void 0;cNE(a)});
_.we(a.channel,"x",b=>{if(b.data){dNE(a);for(let f=0;f<b.data.length;f++){var c=a,d=b.data[f],e=d.speechResults;if(e)a:{const g=[];d=[];let h=!1;for(const k of e){if(k.noSpeech){cNE(c);c.errorHandler("NO_SPEECH");break a}k.transcript!==void 0&&k.stability!==void 0&&(k.stability<c.Pa&&(h=!0),h?d.push(k.transcript):g.push(k.transcript))}if(g.length!==0||d.length!==0)e=g.join(" "),d=d.join(" "),c.Ka?c.completeHandler(e,d):c.transcriptionUpdateHandler(e,d)}else d.eventType==="END_OF_UTTERANCE"?c.Ka=!0:
(c.errorHandler("UNEXPECTED_ASSISTANT_RESPONSE"),c.logError("UNEXPECTED_ASSISTANT_RESPONSE"))}}});_.we(a.channel,"w",b=>{cNE(a);switch(b.status){case 1:b="WEBCHANNEL_NETWORK_ERROR";break;case 2:b="WEBCHANNEL_SERVER_ERROR";break;default:b="WEBCHANNEL_UNKNOWN_ERROR"}a.errorHandler(b);a.logError(b)})},fNE=function(a){dNE(a);a.Ca=(0,_.Vn)(()=>{cNE(a);a.errorHandler("NO_SPEECH")},11E3)},cNE=function(a){dNE(a);a.Ea();a.channel&&(a.Ba=!1,a.channel.close(),a.channel=void 0);a.state=0;a.stopHandler()},gNE=
function(a,b){a.Ba&&(a.state!==2&&(a.state=2,a.listeningHandler()),b=new Uint8Array(b),b='{ "audioIn": "'+_.La(b)+'" }',a.channel.send(b))},dNE=function(a){a.Ca!==null&&((0,_.Wn)(a.Ca),a.Ca=null)},hNE=class{constructor(a,b,c=.5){this.apiKey=a;this.endpoint=b;this.Pa=c;this.stream=null;this.state=0;this.Ba=!1;this.languageCode="en-us";this.listeningHandler=()=>{};this.audioDetectedHandler=()=>{};this.completeHandler=()=>{};this.errorHandler=()=>{};this.stopHandler=()=>{};this.transcriptionUpdateHandler=
()=>{};this.Ca=null;this.Ka=!1;this.Ma=_.Ng();_.p$o()}start(a){this.state===0&&(this.Na()?(this.state=1,this.Ka=!1,this.languageCode=a.languageCode||"en-US",this.listeningHandler=a.listeningHandler||this.listeningHandler,this.audioDetectedHandler=a.audioDetectedHandler||this.audioDetectedHandler,this.stopHandler=a.stopHandler||this.stopHandler,this.completeHandler=a.completeHandler||this.completeHandler,this.errorHandler=a.errorHandler||this.errorHandler,this.transcriptionUpdateHandler=a.transcriptionUpdateHandler||
this.transcriptionUpdateHandler,eNE(this),this.Da(),fNE(this)):this.errorHandler("OFFLINE"))}stop(){this.state!==0&&(cNE(this),this.errorHandler("ABORTED"))}getState(){return this.state}Ea(){}Da(){return _.lg(null)}logError(a,b=""){this.Ma.Hc("spch-recog",a+b);this.Ma.log()}Na(){return!0}};var jNE=function(a,b){if(a.oa)if(window.OfflineAudioContext){var c=a.oa.sampleRate,d=b.inputBuffer.getChannelData(0);b=new window.OfflineAudioContext(1,d.length,16E3);var e=b.createBuffer(1,d.length,c),f=e.getChannelData(0),g=0;for(let h=0;h<d.length;h++)f[h]=d[h],g+=f[h]*f[h];!a.Ha&&Math.sqrt(g/d.length)>.01&&(a.Ha=!0,a.audioDetectedHandler());d=b.createBufferSource();d.buffer=e;d.connect(b.destination);d.start(0);b.oncomplete=h=>{h=h.renderedBuffer.getChannelData(0);const k=Math.floor(16384E3/c),
l=new Int16Array(k);for(let n=0;n<k;++n)l[n]=Math.max(-1,Math.min(1,h[n]))*32767;gNE(a,l.buffer)};b.startRendering()}else iNE(a,b)},iNE=function(a,b){var c=a.oa.sampleRate,d=b.inputBuffer.getChannelData(0),e=Math.floor((c+8E3)/16E3);c=d.length/e;b=new Float32Array(c);for(let f=0;f<c;++f)b[f]=d[f*e];d=new Int16Array(c);for(e=0;e<c;++e)d[e]=Math.max(-1,Math.min(1,b[e]))*32767;gNE(a,d.buffer)},kNE=class extends hNE{constructor(){super(...arguments);this.oa=this.Aa=null;this.Ha=!1}Da(){if(!navigator||
!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia)return _.rh(Error("gF"));this.oa=new (window.AudioContext||window.webkitAudioContext)({latencyHint:"interactive"});this.Aa=this.oa.createScriptProcessor(1024,1,1);this.Aa.onaudioprocess=c=>{jNE(this,c)};this.Aa.connect(this.oa.destination);const a=c=>{this.stream=c;if(!this.oa)return _.lg();c=this.oa.createMediaStreamSource(c);this.Aa&&c.connect(this.Aa);return _.lg()},b={audio:{sampleSize:16,channelCount:1},video:!1};this.stream?a(this.stream):
navigator.mediaDevices.getUserMedia(b).then(a).catch(c=>{cNE(this);c.name&&c.name==="NotAllowedError"?this.errorHandler("NO_MICROPHONE_PERMISSION"):(this.errorHandler("AUDIO_ERROR"),this.logError("AUDIO_ERROR",c.message))});return super.Da()}Ea(){this.oa&&(this.oa.state==="running"&&this.Aa&&(this.Aa.onaudioprocess=()=>{}),this.oa.close(),this.oa=null,this.stream&&(this.stream.getAudioTracks().forEach(a=>{a.stop()}),this.stream=null));this.Aa=null;this.Ha=!1;super.Ea()}Na(){return navigator.onLine}};var lNE=class extends _.RLE{constructor(a){super(a);this.Wob=new kNE(this.flags.ak,"https://embeddedassistant-webchannel.googleapis.com/google.assistant.embedded.v1.EmbeddedAssistant/Assist/channel");this.oa={languageCode:this.language,listeningHandler:this.listeningStartHandler,transcriptionUpdateHandler:(b,c)=>{this.recognitionResultHandler(b+c,b,!1)},errorHandler:b=>{const [c,d]=bNE(b);this.errorHandler(c,void 0,d)},completeHandler:(b,c)=>{this.recognitionResultHandler(b+c,b,!0)}}}initialize(){}isInitialized(){return!0}start(){this.Wob.start(this.oa)}stop(){this.Wob.getState()!==
0&&this.Wob.stop()}};_.lLE.set(1,function(a){return new lNE(a)});
_.v();
});
// Google Inc.
