loaded_h_0(function(_){var window=this;
var Wjr,Xjr;Wjr=function(a){return{n7:Number(a.get("backoff")),hLc:Number(a.get("last-rej"))}};Xjr=function(a,{n7:b,hLc:c}){a.set("backoff",b)&&a.set("last-rej",c)};
_.Yjr=class{constructor(a,b){this.storage=a;this.oa=b}async Y0a(){if(!this.storage)return[2];const {n7:a,hLc:b}=Wjr(this.storage),c=Number(this.oa.Aa());return a&&b&&Date.now()-b<Math.min(a,c)?[1]:[0,2]}KEb(a,b){if(this.storage)if(a){var c=this.storage;c.remove("backoff");c.remove("last-rej")}else b&&({n7:a}=Wjr(this.storage),a?c=Math.max(a,Math.min(Number(this.oa.Ba())*a,Number(this.oa.Aa()))):c=Number(this.oa.Ca()),Xjr(this.storage,{n7:c,hLc:Date.now()}))}};_.Zjr=class{constructor(a,b,c){this.storage=a;this.ei=b;this.oa=c}async Y0a(){try{if(!_.qna())return[7];if(_.ca.lpt)return[5];if(!this.storage)return[2];{const d=this.storage.get("last-ei");var a=d instanceof Array?d:[];if(a.indexOf(this.ei)!==-1)var b=!1;else{for(a.push(this.ei);a.length>3;)a.shift();this.storage.set("last-ei",a);b=!0}}if(!b)return[6];const c=_.y(await _.y(this.oa.Y0a()));[b]=c;b===0&&(_.ca.lpt=!0);return c}finally{_.y()}}KEb(a,b){this.oa.KEb(a,b)}};
_.Vjr=_.x("KHourd",[]);
var Gjr,Jjr;_.Ejr=function(){let a;try{a=window.performance.now()}catch(b){return}return _.eod((new _.Cr).setSeconds(Math.floor(a/1E3)),a%1E3*1E6)};_.Fjr=function(a){switch(a){case 0:return 1;case 1:return 3;case 2:return 4;case 3:return 5;case 5:return 6;case 6:return 7;case 7:return 8;case 8:return 9;case 9:return 10;case 100:return 100;case 101:return 101;default:return 0}};Gjr=function(a){a.oa&&google.caft&&google.caft(()=>{(0,_.sf)(()=>{a.flush()})})};
_.Ijr=function(a,b,c,d,e,f,g=!0){return window.btoa?new Hjr(a,c,b,d,e,f,g):null};Jjr=async function(a){try{const b=_.ac().oa,c=_.y(await _.y(_.Kf(_.ojr,b))),d=_.y(await _.y(_.Kf(_.Zq,b))),e=_.B(a,76)?_.y(await _.y(_.Kf(_.p7a,b))):void 0;return{uoa:c,kc:d,Mv:e}}finally{_.y()}};_.Mjr=function(a,b){if(!_.B(a,21))return new Kjr;a=Jjr(a);return new Ljr(b,a)};_.Njr=class extends _.m{constructor(a){super(a)}Ca(){return _.kj(this,1)}Aa(){return _.kj(this,2)}Ba(){return _.lj(this,3)}};_.Ojr=class extends _.m{constructor(a){super(a)}};
_.Ojr.prototype.qb="C4mkuf";_.Pjr=class{constructor(a){this.error=a}};var Rjr=async function(a,[b,c]){try{var d=a.logger;d.oa=!0;var e=_.Jh(d.Aa,1,_.Fjr(b)),f=_.Ejr();_.Ob(e,_.Cr,12,f);let g;(g=d.counters)==null||g.nle(b);if(b===0)return a.prompt(c);_.y(await _.y(Qjr(a)));Gjr(a.logger);return new _.Pjr(null)}finally{_.y()}},Qjr=async function(a){try{const b=_.y(await _.y(a.Pta.MDa()));_.Shr(b)!==3&&_.Shr(b)!==6||_.Nhr()}finally{_.y()}},Sjr=async function(a,b){try{_.y(await _.y(a.Pta.JEb()));var c=b.OLb;const f=_.mj(a.config,62)||0;a.oa.write(c,f);var d=b.dyd;var e=
d?d===2:a.Pta.j4a();a.Dkb.KEb(!0,e);e&&_.qir(a.logger,!0);_.y(await _.y(a.logger.flush()));e&&_.y(await _.y(a.Ba.cud()));return new _.Pjr(null)}finally{_.y()}},Tjr=async function(a,b){try{const c=_.kir(b);_.y(await _.y(a.Pta.IEb(c)));_.kir(c).oa()&&_.Nhr();const d=!c.oa(),e=a.Pta.j4a();a.Dkb.KEb(d,e);e&&_.qir(a.logger,d);_.y(await _.y(a.logger.flush()));_.y(await _.y(a.Pta.Ba()));return new _.Pjr(new _.jir(c.code,c.message))}finally{_.y()}},Hjr=class{constructor(a,b,c,d,e,f,g=!0){this.config=a;this.Dkb=
b;this.logger=c;this.Pta=d;this.Aa=e;this.Ba=f;this.oa=new _.nir(!0,g)}async start(){try{if(!_.Lhr(_.mj(this.config,62))){var a=this.logger;a.oa=!0;_.Lh(a.Aa,2,!0)}const b=_.y(await _.y(this.Dkb.Y0a()));return Rjr(this,b)}finally{_.y()}}async prompt(a){try{_.y(await _.y(this.Pta.dXa()));Gjr(this.logger);try{const b=_.y(await _.y((new _.oir(this.Aa)).getCurrentPosition(a,3)));return Sjr(this,b)}catch(b){return _.y(),Tjr(this,b)}}finally{_.y()}}};_.Ujr=class{async Y0a(){return[0,2]}KEb(){}};var Kjr=class{async cud(){}},Ljr=class{constructor(a,b){this.ei=a;this.oa=b}async cud(){try{const a=_.y(await _.y(this.oa)),b=a.uoa.oa(new Map([["sei",this.ei],["dlnr","1"]]));if(a.Mv)try{_.y(await _.y(a.Mv.transition(b.toString())));return}catch(c){_.y(),_.$e(Error("Ew`"+c))}a.kc.navigateTo(b,!1)}finally{_.y()}}};
_.t("KHourd");
var dkr=function(a,b){var c=_.ij(a,72);if(_.B(a,44)||!c)c=void 0;else{var d=new _.a7a(1655);c=new $jr(d,c)}c=new _.rir(b.Ohc,c);d=_.mj(a,62);var e=(new akr).create();if(e){var f=_.Lhr(d);e=new _.uir(e,c);d=f&&d!==2?new _.Eir(f,c):void 0;d=new _.zir(e,c,d)}else d=null;if(!d)return null;f=(new bkr).from(a,b.ei,d);if(!f)return null;e=(new ckr).from(a);if(!e)return null;b=_.Mjr(a,b.ei);return _.Ijr(a,c,f,d,e,b)},ekr=async function(a,b){let c;return((c=dkr(a,b))==null?void 0:c.start())||new _.Pjr(null)},
fkr=function(a){_.we(document,"visibilitychange",()=>{document.visibilityState==="visible"&&a()})},gkr={PROMPT:0,ppf:1,spf:2,rpf:3,opf:5,tpf:6,qpf:7,upf:8,npf:9,etf:100,mpf:101,0:"PROMPT",1:"NO_PROMPT_BACKOFF",2:"NO_PROMPT_NO_STORAGE",3:"NO_PROMPT_NOT_GRANTED",5:"NO_PROMPT_ALREADY_OPEN",6:"NO_PROMPT_SAME_EVENT",7:"NO_PROMPT_NOT_DIRECT_NAVIGATION",8:"NO_PROMPT_THROTTLED",9:"NO_PRE_PROMPT_GRANTED",100:"PRE_PROMPT",101:"NO_PRE_PROMPT_DENIED"},akr=class{create(){for(const a of _.Ze(_.vir)){const b=a.create();
if(b)return b}return null}},hkr=class{constructor(a){this.oa=a;_.vo(a,"/client_streamz/location/location_prompt/prompt_decisions_count",_.$b("decision"),_.$b("browser"))}Vj(a,b){_.xo(this.oa,"/client_streamz/location/location_prompt/prompt_decisions_count",a,b)}},ikr=class{constructor(a){this.oa=a;_.vo(a,"/client_streamz/location/location_prompt/prompt_responses_count",_.$b("response"),_.$b("browser"))}Vj(a,b){_.xo(this.oa,"/client_streamz/location/location_prompt/prompt_responses_count",a,b)}};var ckr;_.jkr=new _.Nn;ckr=class{from(a){for(const b of _.Ze(_.jkr)){const c=b.from(a);if(c)return c}return null}};var $jr=class{constructor(a,b){this.oa=new _.yQa(a);this.Ba=new hkr(this.oa);this.Ca=new ikr(this.oa);this.Aa=b||"UNKNOWN_BROWSER"}nle(a){this.Ba.Vj(gkr[a],this.Aa)}ole(a){this.Ca.Vj(a?"ACCEPTED":"DENIED",this.Aa)}flush(){this.oa.oa()}};var bkr;_.kkr=new _.Nn;bkr=class{from(a,b,c){if(_.mj(a,11)===2)return new _.Ujr;for(const d of _.Ze(_.kkr)){const e=d.from(a,b,c);if(e)return e}return null}};var lkr=async function(a,b,c){try{const d=a.getRoot().el();_.y(await _.y(ekr(b,{ei:c,Ohc:d})))}finally{_.y()}};_.cs(_.Vjr,class extends _.as{static Sa(){return{jsdata:{wqe:_.Ojr}}}constructor(a){super(a.Oa);const b=a.jsdata.wqe,c=google.getEI(this.getRoot().el());lkr(this,b,c);_.B(b,61)&&fkr(function(){ekr(b,{ei:c})})}});
var mkr=function(a){return new Promise((b,c)=>{navigator.geolocation.getCurrentPosition(b,c,a)})},nkr=_.Ra(function(a){return(0,_.lCa)(a)&&(0,_.fca)(a.code)&&(0,_.eca)(a.message)?!0:!1}),okr=class{async getCurrentPosition(a,b,c){try{const d=c?{timeout:c.timeoutMillis,maximumAge:c.Czb,enableHighAccuracy:!!c.enableHighAccuracy}:{timeout:b,maximumAge:15E3};try{const e=_.y(await _.y(mkr(d)));if(!e)throw new _.jir(2,"The HTML5 geolocation API returned null or undefined.");return{OLb:e}}catch(e){throw _.y(),
a=e,a instanceof _.jir?a:nkr(a)?new _.jir(a.code,a.message):new _.jir(2,`The HTML5 geolocation API returned an unknown error: ${a}`);}}finally{_.y()}}};var pkr=class{from(){let a,b;return((a=navigator)==null?0:(b=a.geolocation)==null?0:b.getCurrentPosition)?new okr:null}};_.hir&&_.Ln(_.jkr,pkr);var qkr=class{from(){return _.Qir()}};_.iir&&_.Ln(_.jkr,qkr);
_.Ln(_.kkr,class{from(a,b){if(_.mj(a,11)!==4)return null;const c=_.Lhr(_.mj(a,62));if(!c)return null;a=_.p(a,_.Njr,47);return new _.Zjr(c,b,new _.Yjr(c,a))}});

var rkr=class{constructor(a){this.Pta=a}async Y0a(){try{return _.Shr(_.y(await _.y(this.Pta.MDa())))===2?[0,1]:[3]}finally{_.y()}}KEb(){}};_.Ln(_.kkr,class{from(a,b,c){return _.mj(a,11)===3&&c?new rkr(c):null}});
_.v();
_.TEs=_.x("T5VV",[]);
_.t("T5VV");
var UEs=function(a){switch(a){case 0:return"BLUR";case 4:return"OFF";case 1:case 2:case 3:return"FILTER";default:return"UNKNOWN"}};_.cs(_.TEs,class extends _.as{static Sa(){return{}}constructor(a){super(a.Oa);this.oa=_.Ld(this.getData("ssc"),-1);this.Aa=_.Sh(this.getData("ssl"),!1);this.Ba=_.Ql(this.getData("ssor"),"");typeof window.google!=="undefined"&&(window.google.sss=UEs(this.oa),window.google.sso=this.Aa,window.google.ssor=this.Ba)}});
_.v();
_.Gkq=_.x("aDVF7",[]);
_.t("aDVF7");
_.cs(_.Gkq,class extends _.as{static Sa(){return{}}constructor(a){super(a.Oa);this.oa=_.Ql(this.getData("len"),"");typeof window.google!=="undefined"&&(a=this.oa.slice(-1),window.google.len=a===","?this.oa.slice(0,-1):this.oa)}});
_.v();
_.GoC=_.x("rhYw1b",[]);
_.t("rhYw1b");
_.cs(_.GoC,class extends _.as{static Sa(){return{}}constructor(a){super(a.Oa);this.oa=_.Ql(this.getData("dmd"),"");this.deviceType=_.Ql(this.getData("dvt"),"");a=_.l1(1);const b=_.l1(0);a=Math.max(a,b);this.Ba=a<=800?"xs":a<=1E3?"s":a<=1300?"m":a<=2E3?"l":"xl";this.Aa=_.Sh(this.getData("iscsc"),!1);typeof window.google!=="undefined"&&(window.google.dvs=this.Ba,window.google.dmd=this.oa,window.google.dvt=this.deviceType,this.Aa&&(window.google.iscsc="1"))}});
_.v();
_.t("IhkWbc");

_.v();
_.aEs=_.x("oPmHrb",[]);
_.$Ds=_.SZb?2291:1926;
_.QDs=_.Okf?800:940;
_.t("oPmHrb");
var bEs=function(a){const b=["script","style","h2"];return a.filter(c=>{const d=c.tagName.toLowerCase();return!b.some(e=>e===d)&&c.hasChildNodes()})},cEs=function(a){return a.getAttribute("data-rrhs")==="1"};var eEs=function(a){if(a.oa){var b=Array.from(a.oa.children),c=_.am("jOAHU");c&&(b=b.filter(g=>g!==c).concat(Array.from(c.children)));var d=bEs(b),e=d.some(g=>!cEs(g)&&!g.classList.contains("SjLxGf"));a.oa.classList.toggle("jBpNZc",!e);var f;(f=document.getElementById("main"))==null||f.classList.toggle("n48JGd",!e);d.some(g=>!cEs(g)||document.evaluate(`//div[@aria-owns="${g.id}"]`,document,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue===null)||dEs(a,b)}},fEs=function(a){let b=0,c;
const d=(c=a.Ma)==null?void 0:c.map(e=>{var f=e.getAttribute("data-rpos");if(f&&a.Ba){var g=Number(f);for(f=!1;b<a.Ba.length;b++){const h=a.Ba[b],k=h.getAttribute("data-rpos");if(k&&g<=Number(k)){h.insertAdjacentElement("beforebegin",e);f=!0;break}}g=a.Ba[a.Ba.length-1];!f&&g&&g.insertAdjacentElement("afterend",e)}return e});a.Aa&&d&&d.length>0&&(_.Hg(a.Aa,"C6Hrtf"),_.Hg(a.Aa,"O0JaK"));_.G0(_.H0.upb);window.dispatchEvent(new Event("resize"))},gEs=function(a){let b;const c=(b=a.Ma)==null?void 0:b.map(d=>
{let e;(e=a.Na)==null||e.insertAdjacentElement("beforebegin",d);return d});c&&c.length>0&&(a.Aa&&_.Hg(a.Aa,"Zea3Wc"),a.oa&&_.Hg(a.oa,"mWTG5b"));_.G0(_.H0.upb);window.dispatchEvent(new Event("resize"))},hEs=function(a,b){a.Aa&&a.oa&&a.Na&&(b||a.Da?a.Ha():a.Ka())},dEs=function(a,b){let c;(c=a.oa)==null||c.removeAttribute("role");b.filter(d=>d.tagName.toLowerCase()==="h2").forEach(d=>{d.remove()})},jEs=class extends _.as{static Sa(){return{}}constructor(a){super(a.Oa);this.Da=!1;this.Da=!window.matchMedia(`(min-width: ${_.$Ds}px)`).matches&&
_.Sh(this.getData("aop"),!1);this.rF();this.Pa=_.QDs;eEs(this);this.Ha=_.gs(this).Dc(()=>{fEs(this)}).build();this.Ka=_.gs(this).Dc(()=>{gEs(this)}).build();this.Ca=window.matchMedia(`(max-width: ${this.Pa-.02}px)`);this.Ca.addEventListener("change",b=>{hEs(this,b.matches)});this.addOnDisposeCallback(()=>{this.Ca.removeEventListener("change",b=>{hEs(this,b.matches)})});a=_.bm("cnt");this.Ea=new MutationObserver(()=>{this.rF()});this.Ea.observe(a,{childList:!0});hEs(this,this.Ca.matches);_.iEs(this)}rF(){this.Na=
document.getElementById("H3wGC")||void 0;var a=_.am("center_col");a&&(this.Aa=a,this.Ba=this.Aa.getElementsByClassName("A6K0A"),a=_.am("rhs"))&&(this.oa=a,this.Ta=this.oa.getElementsByClassName("A6K0A"),this.Ma=Array.from(this.Ba).concat(Array.from(this.Ta)).filter(cEs).sort((b,c)=>Number(b.getAttribute("data-rpos"))-Number(c.getAttribute("data-rpos"))))}Ub(){this.Ea&&this.Ea.disconnect();super.Ub()}};jEs.prototype.$wa$k4Iseb=function(){return this.Ub};_.iEs=()=>{};_.cs(_.aEs,jEs);
_.v();
_.kEs=_.x("FzTajd",[_.ir]);
_.t("FzTajd");
var lEs=function(a){if(a.size()<2)a.remove();else{let b;(b=a.first())==null||b.remove();let c;(c=a.last())==null||c.remove()}},mEs=class extends _.as{static Sa(){return{service:{Cf:_.Wv}}}constructor(a){super(a.Oa);this.Cf=a.service.Cf;this.Ba();(0,_.sf)(()=>{this.Aa()})}Ba(){const a=document.getElementById(this.getRoot().Tc("aria-owns")||"");a&&(this.oa=new _.mo(a))}Aa(){this.oa!==void 0&&!this.oa.isEmpty()&&this.oa&&!this.oa.closest(".TQc1id").isEmpty()&&_.uPb(this.Cf,this.oa,this.getRoot())}Ca(){if(this.oa!==
void 0&&!this.oa.isEmpty()&&(!this.oa||this.oa.closest(".TQc1id").isEmpty())){var a;(a=this.getRoot().next(".focusSentinel").first())==null||a.remove();var b;(b=this.getRoot().next(".focusSentinel").first())==null||b.remove();lEs(this.oa.children().filter(".focusSentinel"));lEs(this.oa.children().filter(".focusSentinel"))}}};mEs.prototype.$wa$jEKfHe=function(){return this.Ca};mEs.prototype.$wa$NYVLBc=function(){return this.Aa};mEs.prototype.$wa$F0OlHe=function(){return this.Ba};_.cs(_.kEs,mEs);
_.v();
_.RDs=_.x("LnZNCd",[]);
_.t("LnZNCd");
var SDs=class extends _.m{constructor(a){super(a)}};SDs.prototype.qb="Sk13Xb";var TDs=function(a){var b=_.am("center_col");const c=_.am("rhs");if(b){if(a.oa!==b||a.Aa!==c)a.Ha=0;a.oa=b;a.Aa=c!=null?c:void 0;a.Ea=!!_.am("H3wGC");b=(b=_.am("rhs"))?b.classList.contains("e0KErc"):!1;a.Da=b}},WDs=function(a){_.B(a.config,1)||TDs(a);const b=UDs();let c=!0;for(const [,d]of b)if(d.matches){VDs(a);c=!1;break}c&&VDs(a)},UDs=function(){return new Map([[12,window.matchMedia(`(max-width: ${_.QDs-.02}px)`)],[14,window.matchMedia("(max-width: 939.98px)")],[16,window.matchMedia("(max-width: 1163.98px)")]])},
VDs=function(a){XDs(a);a.Ca=(0,_.Vn)(()=>{if((a.Ea||a.Da)&&document.visibilityState!=="hidden"&&a.oa&&!(a.Ha>=_.Je(a.config,2,10))){var b=YDs(),c=_.Ng(),d=!0,e=(h,k)=>{c.Hc(h,k);d=!1},f=a.oa.getBoundingClientRect();if(a.Aa){const h=a.Aa.getBoundingClientRect();var g=Math.round(h.left-f.right);const k=Math.round(h.top-f.top);!(h.width*h.height>1)||Math.abs(k)<2&&Math.abs(g-76)<2||e("errsrp-rhs-p",`t:${k},d:${g}/${b}cols`);a.Ea&&b===12?(Math.abs(f.width-652)<2||e("errsrp-main-w",`${Math.round(f.width)}/${b}cols`),
a.Aa.querySelectorAll('[data-rrhs="1"]').length===0&&a.oa.querySelectorAll('[data-rrhs="1"]').length!==0||e("errsrp-rhs-r","no-reflow")):a.Da&&(g=Math.min(12,Math.max(8,b-6)),Math.abs(f.width-(56*g-20))<2||e("errsrp-main-w",`${Math.round(f.width)}/${b}cols`),Math.abs(h.width-(56*(b-1-g)-20))<2||e("errsrp-rhs-w",`${Math.round(h.width)}/${b}cols`))}else Math.abs(f.width-652)<2||e("errsrp-main-w",`${Math.round(f.width)}/${b}cols`);d||(c.log(),a.Ha++)}},10)},YDs=function(){for(const [a,b]of UDs()){const c=
a;if(b.matches)return c}return 20},XDs=function(a){a.Ca&&((0,_.Wn)(a.Ca),a.Ca=null)},ZDs=class extends _.as{static Sa(){return{jsdata:{GFe:SDs}}}constructor(a){super(a.Oa);this.Da=this.Ea=!1;this.Ha=0;this.config=a.jsdata.GFe;_.B(this.config,1)&&(TDs(this),a=_.bm("cnt"),this.Ba=new MutationObserver(()=>{WDs(this)}),this.Ba.observe(a,{childList:!0}));const b=UDs();for(var [,c]of b)c.addEventListener("change",()=>{VDs(this)});this.addOnDisposeCallback(()=>{for(const [,d]of b)d.removeEventListener("change",
()=>{VDs(this)})});WDs(this);c=_.Ng();c.Hc("errsrp-init","init");c.log()}Ub(){this.Ba&&this.Ba.disconnect();super.Ub()}};ZDs.prototype.$wa$k4Iseb=function(){return this.Ub};_.cs(_.RDs,ZDs);
_.v();
_.t("M6QgBb");

_.v();
_.phe=_.x("EO13pd",[_.mr,_.Zq,_.N0a,_.O0a,_.gr]);
_.nhe=class extends _.m{constructor(a){super(a)}};_.ohe=class extends _.m{constructor(a){super(a)}getInteractionVed(){return _.z(this,4)}};
var lhe;
_.mhe=function(a,b,c,d,e){var f=(a==null?void 0:a.Ea())||"";if(!f){var g,h,k;if(a=(h=(g=a.Ca())==null?void 0:g.yf())==null?void 0:(k=h.Re(_.CF))==null?void 0:k.getImage()){f=a;a=(0,_.fce)(f)?f.getImage():f;g=(f=a.Re(_.MF))&&_.Rg(f,2);h=f&&_.Rg(f,3);k=_.Rg(a,2);var l=a.wJ();a=l?_.Rg(l,1):"";const n=l?_.Lbe(l):"";l=l?_.Kbe(l):"";if(!g||!h||!k)throw Error("Jl");b=new Map([["q",b],["imgurl",a],["imgrefurl",h],["docid",g],["tbnid",k],["vet",1],["w",n],["h",l],["hcb","2"]]);_.B(f,10)&&b.set("itg",1);c&&
(b.set("ved",c),d&&b.set("ictx",d),e&&b.set("vet",e));f=_.zc(lhe,b)}}return f};lhe=(0,_.yc)`/imgres`;
_.ffe=function(a){return(0,_.fce)(a)?a.getId():(0,_.fQc)(a)?a.IV():a.getUniqueId()};
_.t("EO13pd");
var uhe,vhe,whe,xhe,yhe,zhe,Che,Dhe,Ehe,Fhe,Ghe,Hhe,Ihe,Jhe,Khe,Lhe,Mhe,Nhe,Ohe,Phe,Qhe,She,The,Uhe,Whe,$he,Vhe,Xhe,aie,Yhe,Zhe;uhe=class extends _.m{constructor(a){super(a)}};vhe=class extends _.m{constructor(a){super(a)}oX(){return _.z(this,1)}};whe=class extends _.m{constructor(a){super(a)}};xhe=class extends _.m{constructor(a){super(a)}};yhe=class extends _.m{constructor(a){super(a)}Aa(a){return _.Qg(this,1,a)}};zhe=[1,2,3,4];_.Ahe=function(a,b){return _.Lh(a,1,b)};_.Bhe=class extends _.m{constructor(a){super(a)}};
Che=function(a,b){_.Ob(a,uhe,10,b)};Dhe=function(a,b){return _.Ob(a,_.aA,14,b)};Ehe=function(a,b){return _.Ob(a,_.Yz,1,b)};Fhe=class extends _.m{constructor(a){super(a)}bA(){return _.p(this,_.Yz,1)}};Ghe=function(a){var b=new Fhe;return _.Ob(b,_.Yz,1,a)};Hhe=function(a,b){return _.Lh(a,2,b)};Ihe=function(a,b){return _.Qg(a,3,b)};Jhe=function(a,b){return _.Ob(a,_.Sz,4,b)};Khe=function(a,b){_.Ob(a,_.KF,2,b)};Lhe=function(a,b){_.Ob(a,uhe,3,b)};
Mhe=class extends _.m{constructor(a){super(a)}Rca(){return _.$g(this,_.AF,1,_.ah())}};Nhe=function(a,b){return _.Ob(a,_.aA,1,b)};Ohe=class extends _.m{constructor(a){super(a)}};Phe=function(a,b){return _.$i(a,14,_.dge,b)};Qhe=function(a,b){return _.$i(a,16,_.dge,b)};_.Rhe=function(a,b){return _.$i(a,17,_.dge,b)};She=function(a){var b=new _.ege;return _.$i(b,18,_.dge,a)};The=_.Zb(_.nhe);Uhe=_.Zb(_.ohe);
Whe=function(a){_.mh(a,{preload:{u1f:_.ihe}});const b=a.Ab("J7OdWb").el();b.ephUSe=()=>{a.Wdc=!1};_.Nv([new _.Qn(b,"insert")],{yc:b});_.jw(b,a.dxa()).then(c=>{a.jbb=!0;a.Wdc=c}).catch(c=>{a.Wdc=!1;(_.Lna(c)||_.Mna(c))&&Vhe(a);throw c;})};$he=function(a,b){b.subscribe(_.ege.prototype.Ca,(c,d)=>Xhe(a,c,d)).subscribe(_.ege.prototype.Ba,c=>Yhe(c)).subscribe(_.ege.prototype.Aa,c=>Zhe(c))};Vhe=function(a){_.jn(window,"pageshow",b=>{b.persisted&&!a.jbb&&Whe(a)})};
Xhe=async function(a,b,c){try{_.y(await _.y(new Promise(google.dclc)));const d=a.vBd.find(g=>g.bnb.Aa().some(h=>_.ffe(h)===_.z(b,1))),e=new Mhe;let f;((f=a.config)==null?0:_.Fi(f,uhe,123))&&Lhe(e,_.p(a.config,uhe,123));if(d)Khe(_.Ob(e,_.aA,4,d.bnb),d.nbc),_.$i(c,11,_.dge,e);else{const g=(new _.fu(a.history.getCurrentUrl(),{VWa:_.cMa})).oa.get("vssid")||"",h=_.y(await _.y(a.UGd.promise))(g);h&&(_.Ob(e,_.aA,4,h),_.$i(c,11,_.dge,e))}}finally{_.y()}};
aie=function(a,b,c,d,e,f,g,h){var k=new _.$fe;g=_.Ch(k,8,g);g=_.Ch(g,16,_.lh);e=e!=null?e:b==null?void 0:_.hj(b,19);e=_.gi(g,12,e);b&&_.Ob(e,_.KF,6,b);c&&_.Qg(e,7,c);d!=null&&_.Qg(e,17,d);f!=null&&_.gi(e,18,f);a.config&&_.Fi(a.config,uhe,123)&&Che(e,_.p(a.config,uhe,123));h&&_.Qg(e,13,h);return e};
Yhe=async function(a){_.Hi(a,whe,1,zhe)?_.Lq():_.Hi(a,vhe,2,zhe)?(a=_.Ah(a,vhe,2,zhe),_.nn(window,"attn_dom_immersive",!1,new _.qhe(a.oX(),_.B(a,2)))):_.Hi(a,yhe,3,zhe)?(a=_.Ah(a,yhe,3,zhe),a=_.z(a,1),_.jhe(a)):_.Hi(a,xhe,4,zhe)&&_.khe()};Zhe=async function(a){_.Hg(document.body,"xHsTDe",{cnb:_.z(a,1)})};
_.bie=class extends _.as{static Sa(){return{service:{history:_.NF,navigation:_.$v,h_a:_.Wfe,v$a:_.Xfe,window:_.Tu}}}constructor(a){super(a.Oa);this.jbb=!1;this.config=this.a2=null;this.vBd=[];this.Wdc=!0;this.UGd=new _.Mq;this.history=a.service.history;this.kc=a.service.navigation;this.h_a=a.service.h_a;var b=this.v$a=a.service.v$a;b.oa.push(this);b.Aa!=null&&(b.Aa.resolve(this),b.Aa=null);this.C2();this.document=a.service.window.getDocument()}Ub(){var a=this.v$a;const b=a.oa.indexOf(this);b>=0&&
a.oa.splice(b,1);super.Ub()}kme(a){a=The(a.data);this.initialize(_.p(a,_.cA,1),_.p(a,_.aA,2),_.p(a,_.KF,3))}gQb(){if(!this.a2){var a=_.Tfe;a.Fj.oa.HJ()&&_.Go(a.Fj,"uvpbs");this.init();_.the();this.Isd()}}initialize(a,b,c){this.config=a;this.vBd.push({bnb:b,nbc:c});this.gQb()}init(){Whe(this);if(this.a2=_.ige())$he(this,this.a2),this.a2.initialize(_.Tla())}sIe(a){this.UGd.resolve(a)}dxa(){return{lS:!0,PNa:()=>{this.dirty()}}}Isd(){this.a2&&this.a2.Aa&&this.a2.Aa.then(()=>{var a=_.Tfe;a.Fj.oa.HJ()&&
(_.Go(a.Fj,"uvpbe"),a.Fj.log())})}async Svb(a,b,c,d,e,f,g,h,k){try{let l;if(_.oMd&&((l=google)==null?0:l.zl)&&google.zl.qvoc)return google.zl.qvoc=!1,Promise.resolve();const n=Math.round(h);this.h_a.Pc(n);const q=a.Aa()[a.Ji()],r=q==null?void 0:_.Yi(q,_.uu,1,_.aQc).getViewerType();r!==25&&r!==47&&(_.hhe.oa._guestSettings={fetchPriority:"high"});this.lrb();if(!this.a2||!this.Wdc)return Promise.resolve().then(()=>{var A=b==null?void 0:_.Hj(b,19),G=this.kc,L=_.Kn(new _.Dn(this.history.getCurrentUrl()),
"q")||"";(A=_.mhe(q,L,d,A||null))&&G.navigateTo(A)});if(!q)return _.$e(Error("Kl")),Promise.resolve();const u=Dhe(aie(this,b,d,e,f,g,n,k),a);if(c==null?0:_.Fi(c,uhe,123))Che(u,_.p(c,uhe,123));else{let A;((A=this.config)==null?0:_.Fi(A,uhe,123))&&Che(u,_.p(this.config,uhe,123))}_.y(await _.y(this.dkc(u,q,d,b)));this.document.dispatchEvent(new CustomEvent("viewerOpenEventHandled"))}finally{_.y()}}async dkc(a,b,c,d){this.lrb();return this.a2?this.a2.sendMessage((new _.ege).dkc(a),!0).catch(e=>{_.$e(Error("Ml`"+
e.message));var f=d==null?void 0:_.Hj(d,19);e=this.kc;var g=_.Kn(new _.Dn(this.history.getCurrentUrl()),"q")||"";(f=_.mhe(b,g,c,f||null))&&e.navigateTo(f)}):(a=Error("Ll"),_.$e(a),Promise.reject(a))}Ige(a){a=Uhe(a.data);this.Svb(_.p(a,_.aA,1),_.p(a,_.KF,2)||null,null,_.z(a,3)||null,a.getInteractionVed()||null,_.Je(a,5)||null,null,_.lj(a,6),_.z(a,7)||null)}async Kge(a){a=a.data;const b=a.params.Dp;if(!b)return _.$e(Error("Nl")),Promise.resolve();b==null||_.Yi(b,_.uu,1,_.aQc).getViewerType();var c;
const d=Jhe(Ihe(Hhe(Ghe(b),a.Aa),(c=a.oa)==null?void 0:c.id),a.params.rc);b.IV();this.lrb();return this.a2?await this.a2.sendMessage(She(d)).catch(e=>{_.$e(Error("Ol`"+e.message))}):(c=Error("Ll"),_.$e(c),Promise.reject(c))}async Efb(a){try{this.a2&&_.y(await _.y(this.a2.sendMessage(_.Rhe(new _.ege,_.Ahe(new _.Bhe,!!a.data))).catch(b=>{_.$e(Error("Pl`"+b.message))})))}finally{_.y()}}dob(a){this.lrb();return this.a2?this.a2.sendMessage(Phe(new _.ege,Nhe(new Ohe,a))).catch(b=>{_.$e(Error("Ql`"+b.message))}):
(a=Error("Ll"),_.$e(a),Promise.reject(a))}MFc(a){this.lrb();return this.a2?this.a2.sendMessage(Qhe(new _.ege,Ehe(new _.age,a))).catch(b=>{_.$e(Error("Rl`"+b.message))}):(a=Error("Ll"),_.$e(a),Promise.reject(a))}lrb(){this.a2||(_.$e(Error("Sl"),{level:2}),this.gQb())}C2(){}};_.bie.prototype.$wa$npAYtf=function(){return this.C2};_.bie.prototype.$wa$Nj7Yd=function(){return this.lrb};_.bie.prototype.$wa$A1kDjc=function(){return this.Efb};_.bie.prototype.$wa$gj6b3c=function(){return this.Kge};
_.bie.prototype.$wa$dwOkab=function(){return this.Ige};_.bie.prototype.$wa$NMQPwb=function(){return this.Isd};_.bie.prototype.$wa$fjjfVb=function(){return this.gQb};_.bie.prototype.$wa$f0xwYb=function(){return this.kme};_.bie.prototype.$wa$k4Iseb=function(){return this.Ub};_.cs(_.phe,_.bie);
var cie=function(a,b,c){a=new _.In(_.hd(a.url));b=!!a.get("imgrc")&&a.get("imgrc")!=="_";if(a.get("vhid")||b){b=!!a.get("oshop");var d=!!a.get("epd");if(b||d)if(c.userInitiated)a.remove("oshop"),a.remove("oshopproduct"),a.remove("epd"),c=new _.Dn(this.history.getCurrentUrl()),_.Hn(c,a.toString()),this.history.oa(c.toString());else try{const e=_.Ahe(new _.Bhe,!0);this.a2.sendMessage(_.Rhe(new _.ege,e))}catch(e){this.a2.sendMessage((new _.ege).dkc(new _.$fe))}}};_.bie.prototype.C2=function(){this.history.addListener(cie.bind(this))};
_.bie.prototype.$wa$npAYtf=function(){return this.C2};

_.v();
_.dpC=_.x("qCgt4c",[_.W0a]);
_.t("qCgt4c");
_.cs(_.dpC,class extends _.as{static Sa(){return{service:{o9:_.qkD}}}constructor(a){super(a.Oa);this.Oi=a.service.o9}});
_.v();
_.Haq=_.x("I9y8sd",[]);
_.t("I9y8sd");
var Iaq=function(){return google.ht&&google.ht<Date.now()&&!google.fuht?!0:!1},Jaq=function(){return google.lfm&&google.lfm.some(a=>a.ie())},Kaq=function(a){a=getComputedStyle(a);if(a.display==="none")return"display: none";if(Number(a.opacity)<.5)return`opacity: ${a.opacity}`;if(a.visibility==="hidden")return"visibility: hidden"},Laq=function(a,b,c,d,{logError:e}){d=_.Xe(d);b=`${b}-${c}-${_.Ina(d)}`;const f=a.get(b),g=_.Ye(d,"am");if(g){if(f){if(g===f)return;let h=`k=${_.Ina(d)}`;(d=_.Ye(d,"ck"))&&
(h=`${h}.ck=${d}`);e(Error("kv`"+JSON.stringify({type:c,sXf:h,BUf:f,iUf:g})))}a.set(b,g)}},Naq=function(a){if(a.toggle){var b;a.sampleRate=(b=a.sampleRate)!=null?b:.01;Maq.push(a)}},Oaq={name:"umods"},Paq=!!(_.qi[18]>>22&1),Qaq=!!(_.qi[18]>>23&1),Raq=!!(_.qi[18]>>24&1),Saq=!!(_.qi[18]>>25&1),Taq=!!(_.qi[18]>>26&1),Uaq=!!(_.qi[18]>>27&1),Vaq=!!(_.qi[18]>>28&1);var Waq=["google.com","youtube.com","ampproject.org",(new URL(location.href)).host];var Maq=[],Xaq=[],Yaq=class extends _.as{static Sa(){return{}}constructor(a){super(a.Oa);this.Ca=Math.random();this.Aa=!1;this.logError=this.logError.bind(this);window.addEventListener("pagehide",()=>{this.Aa=!0});window.addEventListener("pageshow",()=>{this.Aa=!1});google.sx(null,()=>{(0,_.Vn)(()=>{this.Ba()},2E3)})}Ba(){if(!this.Aa)for(const a of Maq)this.sample(a,()=>{a.run({logError:(b,c={})=>{this.logError(a.name,b,c)}})})}logError(a,b,c={}){if(!this.oa){this.oa={};for(const d of Xaq)this.sample(d,
()=>{const e=d.run();e&&(this.oa=Object.assign({},this.oa,e))})}_.$e(b,{level:0,Gf:Object.assign({},{src:"bad_srp_detection"},c,this.oa)});Qaq&&navigator.sendBeacon(`/gen_204?atyp=i&bsf=${a}.1&ei=${(0,_.Xl.Xu)()}`,"")}sample(a,b){((a.yXf?Math.random():this.Ca)<(a.sampleRate||0)||Paq)&&b()}};Yaq.prototype.$wa$rT3LBf=function(){return this.Ba};
Naq({name:"fi",run:function({logError:a}){const b={},c=Array.from(document.querySelectorAll("iframe")).map(d=>{try{return d.src&&d.src.length!==0?(new URL(d.src)).hostname:void 0}catch(e){return e.toString()}}).filter(d=>{if(!d)return!1;d=d.split(".");for(const e of Waq)if(d.slice(-1*e.split(".").length).join(".").toLowerCase()===e)return!1;return!0});if(c.length){b.count=String(c.length);for(let d=0;d<Math.min(c.length,3);d++)b[`iframe_${d+1}`]=c[d];a(Error("lv"),b)}},toggle:Saq});
Naq({name:"hp",run:function({logError:a}){if(!Iaq()){for(var b=document.elementFromPoint(window.innerWidth/2,window.innerHeight/2),c=[];b;)c.unshift(b),b=b.parentElement;for(const d of c){if(d.offsetWidth<window.innerWidth*.6||d.offsetHeight<200)break;const e=Kaq(d);if(e){const f=d;(0,_.Vn)(()=>{e===Kaq(f)&&a(Error("mv"),{hiddenProperty:e,id:f.id,tagName:f.tagName,classes:f.classList.value,styles:f.getAttribute("style")||""})},1E3);break}}}},toggle:Raq});
Naq({name:"sp",run:function({logError:a}){var b;if(b=!Iaq())b=document.body.querySelector("[jsname=KG3hVc]"),b=!(b&&window.getComputedStyle(b).display!=="none")&&!Jaq();if(b){b=document.body.clientHeight;var c,d=((c=document.getElementById("rcnt")||document.getElementById("center_col"))==null?void 0:c.clientHeight)||0;(b<400||d<100)&&a(Error("nv"),{pageHeight:String(b),resultsHeight:String(d)})}},toggle:Raq});
Naq({name:"qm",run:function({logError:a}){document.compatMode==="BackCompat"&&a(Error("ov"))},toggle:Taq});
Naq({name:"um",run:function({logError:a}){var b=google.erd;if(b){var c=b.bv;if(c&&(b=b.dpf)){var d,e=(d=navigator)==null?void 0:d.userAgent;if(e){d=_.dg("s",Oaq);c=`${c}-${b}-${e}`;var f;(b=(f=google.xjs)==null?void 0:f.basejs)&&Laq(d,c,"jsurl",b,{logError:a});var g;(f=(g=google.xjs)==null?void 0:g.basecss)&&Laq(d,c,"cssurl",f,{logError:a});var h;(g=(h=google.xjs)==null?void 0:h.basecomb)&&Laq(d,c,"comburl",g,{logError:a})}}}},toggle:Vaq});
var Zaq={name:"nn",run:function(){var a=document.querySelectorAll("script:not([nonce])");if(a.length!==0){var b={nonce_count:String(a.length)},c=0;for(const d of a){a=d.src;let e;if((e=a)==null?0:e.startsWith("https://www.gstatic.com/"))return;if(c++>3)break;let f;const g=(f=d.textContent)==null?void 0:f.substring(0,300);g&&(b[`nonce_script_${c}`]=g);a&&(b[`nonce_src_${c}`]=a)}return b}},toggle:Uaq};if(Zaq.toggle){var $aq;Zaq.sampleRate=($aq=Zaq.sampleRate)!=null?$aq:1;Xaq.push(Zaq)}_.cs(_.Haq,Yaq);
_.v();
_.t("xBbsrc");
_.K8o=new _.Jf(_.y5a);
_.v();
_.Q8o=_.x("DLOxie",[_.y5a,_.Oq]);
_.t("DLOxie");
var R8o=function(a){try{const b=_.ox(a);return b.hostname!=null&&b.hostname.endsWith(".search.translate.goog")}catch(b){return!1}},S8o=RegExp("^(.+)[.]([a-zA-Z]+)2([a-zA-Z]+)[.]search[.]translate[.]goog");var T8o={childList:!0,subtree:!0,attributes:!0,attributeFilter:["href"]},X8o=function(a,b){if(R8o(b.href))try{var c=b.href;if(!R8o(c))throw Error("bt`"+c);const e=_.ox(c),f=e.hostname.match(S8o);if(!f||f.length!==4)throw Error("ct`"+c);const g=f[1],h=f[2],k=f[3];if(h.length!==2||!/^[a-zA-Z]+$/.test(h))throw Error("dt`"+c);if(k.length!==2||!/^[a-zA-Z]+$/.test(k))throw Error("et`"+c);var d={iha:_.M6b({hostname:g},e).href,E6:h,r4:k};_.Ng().Hc("toledo_url",b.href).log();_.Pc(b,d.iha)}catch(e){}(a.Aa||
a.Ca)&&(d=U8o(a,b))&&(V8o(a,b,d)||W8o(b,d))},U8o=function(a,b){if(!b.href)return null;let c,d;try{b=c=_.ox(b.href);let f=!1;if((b.hostname==="google.com"||b.hostname==="www.google.com"||b.hostname===a.Ac.location.hostname)&&b.pathname==="/url"){f=!0;var e=_.px(b);e.has("q")?b=_.ox(e.get("q")):e.has("url")&&(b=_.ox(e.get("url")))}({url:c,dyb:d}={url:b,dyb:f})}catch(f){return null}if(c.hostname!=="translate.google.com"||c.pathname!=="/translate")return null;a=_.px(c);if(!a.has("u")||!a.has("tl")||!a.has("sl"))return null;
e=a.get("u");e+=c.hash!=="#"?c.hash:"";return{dyb:d,m_b:c.href,N9a:e,wZb:a.get("tl"),KYa:a.get("sl")}},V8o=function(a,b,c){if(!a.oa.isAvailable())return!1;_.Pc(b,c.N9a);b.addEventListener("click",d=>{d.preventDefault();_.Ov(b,{userAction:3,data:{url:c.m_b}});a.oa.oa(c.N9a,c.wZb,c.KYa,_.Hd())});return!0},W8o=function(a,b){HTMLAnchorElement.prototype.hasOwnProperty("hrefTranslate")&&(_.Pc(a,b.N9a),a.setAttribute("hrefTranslate",b.wZb),b.dyb&&a.addEventListener("click",async()=>{try{_.y(await _.y(_.Ov(a,
{userAction:3,data:{url:b.m_b}})))}finally{_.y()}}))},Y8o=class extends _.as{static Sa(){return{service:{zk:_.K8o,Ac:_.Mw}}}constructor(a){super(a.Oa);this.jj=null;this.Ba=b=>{for(const c of b)c.type==="childList"?c.addedNodes.forEach(d=>{d.nodeType===Node.ELEMENT_NODE&&(d.matches("a")&&X8o(this,d),d instanceof Element&&d.querySelectorAll("a").forEach(e=>{X8o(this,e)}))}):c.type==="attributes"&&c.attributeName==="href"&&c.target.matches("a")&&X8o(this,c.target)};this.oa=a.service.zk;this.Ac=a.service.Ac;
this.jj=new MutationObserver(this.Ba);this.Aa=this.getData("cte").Mb();this.Ca=this.getData("ste").Mb()}Xd(){document.documentElement.querySelectorAll("a").forEach(a=>{X8o(this,a)});this.jj.observe(document.body,T8o)}Vc(){super.Vc();this.jj&&this.jj.disconnect()}};Y8o.prototype.$wa$mU5qzf=function(){return this.Vc};Y8o.prototype.$wa$npT2md=function(){return this.Xd};_.cs(_.Q8o,Y8o);
_.v();
});
// Google Inc.
