loaded_h_0(function(_){var window=this;
_.t("vRlMvf");
_.M_c=new _.Jf(_.L0a);
_.v();
_.B1c=_.x("i8S0p",[_.hr,_.L0a]);
_.t("i8S0p");
var f2c=function(a){var b=new _.Uz;var c=_.Fi(a,c2c,32)?1:_.Fi(a,_.v1c,33)?3:2;var d=new _.G1c;c=_.Jh(d,7,c);c=_.Lh(c,4,!0);if(_.Fi(a,c2c,32)){var e,f;d=_.z(a,18);d=_.Qg(c,1,d);var g=(e=_.p(a,c2c,32))==null?void 0:e.xs();e=_.Qg(d,2,g);d=(f=_.p(a,c2c,32))==null?void 0:_.z(f,4);_.Qg(e,3,d);f=_.p(a,c2c,32);_.bh(f,5)&&(f=_.p(a,c2c,32),f=_.z(f,5),_.Qg(c,6,f))}b=_.LB(b,d2c(_.H1c,c));_.Fi(a,c2c,32)&&(c=(new _.I1c).setTitle(_.p(a,c2c,32).getTitle()),f=_.z(a,18),c=_.Qg(c,2,f),f=_.p(a,c2c,32).nj(),c=_.Qg(c,
3,f),_.LB(b,d2c(_.J1c,c)));if(_.Fi(a,_.v1c,33)){var h,k,l,n,q;c=(new _.N1c).setTitle((h=_.p(a,c2c,32))==null?void 0:h.getTitle());h=(k=_.p(a,_.v1c,33))==null?void 0:_.p(k,_.J_c,4);k=_.Ob(c,_.J_c,3,h);h=(l=_.p(a,_.v1c,33))==null?void 0:_.p(l,_.L1c,3);l=_.Ob(k,_.L1c,10,h);k=(n=_.p(a,_.v1c,33))==null?void 0:n.xH();n=_.Ob(l,_.g1c,14,k);l=(q=_.p(a,_.v1c,33))==null?void 0:_.p(q,_.M1c,11);q=_.Ob(n,_.M1c,16,l);let X;switch((X=_.p(a,_.v1c,33))==null?void 0:_.mj(X,9)){case 2:var r,u=(r=_.p(a,_.v1c,33))==null?
void 0:r.mG();_.Ob(q,_.e1c,12,u);break;case 3:r=(u=_.p(a,_.v1c,33))==null?void 0:_.p(u,_.lC,10),_.Ob(q,_.lC,15,r)}_.LB(b,d2c(_.O1c,q))}var A,G,L,N,T;r=new _.P1c;u=(A=_.p(a,e2c,23))==null?void 0:_.p(A,_.Wg,7);A=_.Ob(r,_.Wg,2,u);r=(G=_.p(a,e2c,23))==null?void 0:_.mj(G,12);G=_.Jh(A,15,r);A=(L=_.p(a,e2c,23))==null?void 0:_.z(L,9);L=_.Qg(G,11,A);G=(N=_.p(a,e2c,23))==null?void 0:_.mj(N,11);N=_.Jh(L,14,G);L=(T=_.p(a,e2c,23))==null?void 0:_.z(T,8);T=_.Qg(N,3,L);N=_.Fi(a,_.v1c,33);T=_.Lh(T,12,N);a=_.Fi(a,
c2c,32);a=_.Lh(T,13,a);_.LB(b,d2c(_.Q1c,a));return d2c(_.F1c,new _.E1c).Aa(b)},d2c=function(a,b){return _.MB(new _.Sz,(new _.Qz).oa(a,b))},e2c=class extends _.m{constructor(a){super(a)}UK(){return _.z(this,3)}},c2c=class extends _.m{constructor(a){super(a)}getTitle(){return _.z(this,1)}setTitle(a){return _.Qg(this,1,a)}xd(){return _.bh(this,1)}nj(){return _.z(this,2)}xs(){return _.z(this,3)}kM(){return _.bh(this,3)}},g2c=function(a,b){return _.Ob(a,_.Sz,1,b)},h2c=function(a,b){return _.Qg(a,2,b)};var i2c=class extends _.as{static Sa(){return{jsdata:{V1c:_.oC},service:{Oi:_.iC,Xtc:_.M_c}}}constructor(a){super(a.Oa);this.yc=null;this.V1c=a.jsdata.V1c;this.Oi=a.service.Oi;this.Xtc=a.service.Xtc}async Pc(a){try{a.event&&a.event.preventDefault();const b=a.rb.el();this.yc=b.querySelector('[role="button"]')||b;const c=a.rb.el(),d=h2c(g2c(new _.D1c,f2c(this.V1c)),this.getRoot().el().id),e=this.Xtc.getInstance(d,()=>{this.yc&&(this.yc.focus(),this.yc=null)});_.y(await _.y(this.Oi.showViewer({viewerType:47,
entrypoint:c,modality:_.Zw?2:1,dD:e,QT:_.A1c?_.a2c:void 0})))}finally{_.y()}}};i2c.prototype.$wa$h5M12e=function(){return this.Pc};_.cs(_.B1c,i2c);
_.v();
});
// Google Inc.
